### ISSUE TITLE
Mopidy Crashing on Raspberry Pi 2B

### ISSUE THREAD

**Issue by artistro08** [mopidy/mopidy#1017]
Mopidy crashes out of nowhere. after I run ` service mopidy run -v` i get this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/mopidy", line 9, in <module>
    load_entry_point('Mopidy==0.19.5', 'console_scripts', 'mopidy')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 521, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2632, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2312, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2318, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/mopidy/__main__.py", line 28, in <module>
    from mopidy import commands, config as config_lib, ext
  File "/usr/local/lib/python2.7/dist-packages/mopidy/commands.py", line 14, in <module>
    from mopidy.audio import Audio
  File "/usr/local/lib/python2.7/dist-packages/mopidy/audio/__init__.py", line 4, in <module>
    from .actor import Audio
  File "/usr/local/lib/python2.7/dist-packages/mopidy/audio/actor.py", line 9, in <module>
    import gst  # noqa
  File "/usr/lib/python2.7/dist-packages/gst-0.10/gst/__init__.py", line 193, in <module>
    from _gst import *
ImportError: /usr/lib/arm-linux-gnueabihf/libxml2.so.2: undefined symbol: xmlDefaultBufferSize, version LIBXML2_2.4.30

```

when I reboot the pi, it works but then crashes over time. any idea why?

I want to add that I'm overclocked slightly:

```
arm_freq=1000
core_freq=500
sdram_freq=500
over_voltage=2

```
and the filesystem is moved to a 3TB hard drive

**Comment by kingosticks** [comment]
Resolved as an overclocking issue, not a Mopidy bug. https://github.com/woutervanwijk/Pi-MusicBox/issues/235
