### ISSUE TITLE
Application error on OSX from core.playback.play(tl_track)

### ISSUE THREAD

**Issue by fatg3erman** [mopidy/mopidy#1091]
Everything was working fine. Then I did "brew update" and "brew upgrade" which gave me mopidy 1.0.0. 
Now when my HTTP API  client calls mopidy.playback.play() then I get an Application Error reported in the browser's error console:

    "<ActorProxy for LocalBackend (urn:uuid:60bdd656-0af6-452c-a898-503391d099dd), attr_path=('playback',)> has no attribute "prepare_change""

    "Traceback (most recent call last):
    File "/usr/local/lib/python2.7/site-packages/mopidy/utils/jsonrpc.py", line 132, in _handle_single_request
      result = self._unwrap_result(result)
    File "/usr/local/lib/python2.7/site-packages/mopidy/utils/jsonrpc.py", line 221, in _unwrap_result
    result = result.get()
    File "/usr/local/lib/python2.7/site-packages/pykka/future.py", line 299, in get
      exec('raise exc_info[0], exc_info[1], exc_info[2]')
    File "/usr/local/lib/python2.7/site-packages/pykka/actor.py", line 200, in _actor_loop
      response = self._handle_receive(message)
    File "/usr/local/lib/python2.7/site-packages/pykka/actor.py", line 294, in _handle_receive
      return callee(*message['args'], **message['kwargs'])
    File "/usr/local/lib/python2.7/site-packages/mopidy/core/playback.py", line 277, in play
      self._play(tl_track, on_error_step=1)
    File "/usr/local/lib/python2.7/site-packages/mopidy/core/playback.py", line 310, in _play
      backend.playback.prepare_change()
    File "/usr/local/lib/python2.7/site-packages/pykka/proxy.py", line 161, in __getattr__
      raise AttributeError('%s has no attribute "%s"' % (self, name))
    AttributeError: ActorProxy for LocalBackend (urn:uuid:60bdd656-0af6-452c-a898-503391d099dd), attr_path=('playback',) has no attribute "prepare_change"

Doesn't matter which backend I use, they all give the same error. Could this be some kind of installation problem? The same client works fine when mopidy is running on Ubuntu, it's just OSX (Yosemite).

**Comment by kingosticks** [comment]
In Mopidy v1.0 the play function takes no arguments. It's documented with all the other changes at https://docs.mopidy.com/en/latest/changelog/. Perhaps your other system is still running Mopidy 0.19.5?

**Comment by jodal** [comment]
It's only the backend playback API that no longer takes a track. Clients
should work unchanged as there's mostly depredations in the core API.

This issue sounds exactly like mopidy/homebrew-mopidy#3.

**Comment by fatg3erman** [comment]
Yep, that was it. Removing the old .pyc files solved it. Thanks.

**Comment by kingosticks** [comment]
Oops, a client, sorry!
