### ISSUE TITLE
Playing local track throws error in Mopidy 1.0

### ISSUE THREAD

**Issue by morgoth** [mopidy/mopidy#1092]
After upgrading Mopidy to 1.0, when I start track taken from local backend, I get error (from var/log/mopidy/mopidy.log):
```
2015-03-30 15:10:15,114 ERROR [12549:MpdSession-55] pykka: Unhandled exception in MpdSession (urn:uuid:60a9863b-c656-435d-8d82-f79ec7c89bcb):
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 200, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 303, in _handle_receive
    return self.on_receive(message)
  File "/usr/local/lib/python2.7/dist-packages/mopidy/utils/network.py", line 367, in on_receive
    self.on_line_received(line)
  File "/usr/local/lib/python2.7/dist-packages/mopidy/mpd/session.py", line 33, in on_line_received
    response = self.dispatcher.handle_request(line)
  File "/usr/local/lib/python2.7/dist-packages/mopidy/mpd/dispatcher.py", line 46, in handle_request
    return self._call_next_filter(request, response, filter_chain)
  File "/usr/local/lib/python2.7/dist-packages/mopidy/mpd/dispatcher.py", line 67, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/usr/local/lib/python2.7/dist-packages/mopidy/mpd/dispatcher.py", line 75, in _catch_mpd_ack_errors_filter
    return self._call_next_filter(request, response, filter_chain)
  File "/usr/local/lib/python2.7/dist-packages/mopidy/mpd/dispatcher.py", line 67, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/usr/local/lib/python2.7/dist-packages/mopidy/mpd/dispatcher.py", line 85, in _authenticate_filter
    return self._call_next_filter(request, response, filter_chain)
  File "/usr/local/lib/python2.7/dist-packages/mopidy/mpd/dispatcher.py", line 67, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/usr/local/lib/python2.7/dist-packages/mopidy/mpd/dispatcher.py", line 104, in _command_list_filter
    response = self._call_next_filter(request, response, filter_chain)
  File "/usr/local/lib/python2.7/dist-packages/mopidy/mpd/dispatcher.py", line 67, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/usr/local/lib/python2.7/dist-packages/mopidy/mpd/dispatcher.py", line 133, in _idle_filter
    response = self._call_next_filter(request, response, filter_chain)
  File "/usr/local/lib/python2.7/dist-packages/mopidy/mpd/dispatcher.py", line 67, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/usr/local/lib/python2.7/dist-packages/mopidy/mpd/dispatcher.py", line 146, in _add_ok_filter
    response = self._call_next_filter(request, response, filter_chain)
  File "/usr/local/lib/python2.7/dist-packages/mopidy/mpd/dispatcher.py", line 67, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/usr/local/lib/python2.7/dist-packages/mopidy/mpd/dispatcher.py", line 158, in _call_handler_filter
    response = self._format_response(self._call_handler(request))
  File "/usr/local/lib/python2.7/dist-packages/mopidy/mpd/dispatcher.py", line 172, in _call_handler
    return protocol.commands.call(tokens, context=self.context)
  File "/usr/local/lib/python2.7/dist-packages/mopidy/mpd/protocol/__init__.py", line 178, in call
    return self.handlers[tokens[0]](context, *tokens[1:])
  File "/usr/local/lib/python2.7/dist-packages/mopidy/mpd/protocol/__init__.py", line 156, in validate
    return func(**callargs)
  File "/usr/local/lib/python2.7/dist-packages/mopidy/mpd/protocol/command_list.py", line 42, in command_list_end
    command, current_command_list_index=index)
  File "/usr/local/lib/python2.7/dist-packages/mopidy/mpd/dispatcher.py", line 46, in handle_request
    return self._call_next_filter(request, response, filter_chain)
  File "/usr/local/lib/python2.7/dist-packages/mopidy/mpd/dispatcher.py", line 67, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/usr/local/lib/python2.7/dist-packages/mopidy/mpd/dispatcher.py", line 75, in _catch_mpd_ack_errors_filter
    return self._call_next_filter(request, response, filter_chain)
  File "/usr/local/lib/python2.7/dist-packages/mopidy/mpd/dispatcher.py", line 67, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/usr/local/lib/python2.7/dist-packages/mopidy/mpd/dispatcher.py", line 85, in _authenticate_filter
    return self._call_next_filter(request, response, filter_chain)
  File "/usr/local/lib/python2.7/dist-packages/mopidy/mpd/dispatcher.py", line 67, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/usr/local/lib/python2.7/dist-packages/mopidy/mpd/dispatcher.py", line 104, in _command_list_filter
    response = self._call_next_filter(request, response, filter_chain)
  File "/usr/local/lib/python2.7/dist-packages/mopidy/mpd/dispatcher.py", line 67, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/usr/local/lib/python2.7/dist-packages/mopidy/mpd/dispatcher.py", line 133, in _idle_filter
    response = self._call_next_filter(request, response, filter_chain)
  File "/usr/local/lib/python2.7/dist-packages/mopidy/mpd/dispatcher.py", line 67, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/usr/local/lib/python2.7/dist-packages/mopidy/mpd/dispatcher.py", line 146, in _add_ok_filter
    response = self._call_next_filter(request, response, filter_chain)
  File "/usr/local/lib/python2.7/dist-packages/mopidy/mpd/dispatcher.py", line 67, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/usr/local/lib/python2.7/dist-packages/mopidy/mpd/dispatcher.py", line 158, in _call_handler_filter
    response = self._format_response(self._call_handler(request))
  File "/usr/local/lib/python2.7/dist-packages/mopidy/mpd/dispatcher.py", line 172, in _call_handler
    return protocol.commands.call(tokens, context=self.context)
  File "/usr/local/lib/python2.7/dist-packages/mopidy/mpd/protocol/__init__.py", line 178, in call
    return self.handlers[tokens[0]](context, *tokens[1:])
  File "/usr/local/lib/python2.7/dist-packages/mopidy/mpd/protocol/__init__.py", line 156, in validate
    return func(**callargs)
  File "/usr/local/lib/python2.7/dist-packages/mopidy/mpd/protocol/status.py", line 207, in status
    result.append(('time', _status_time(futures)))
  File "/usr/local/lib/python2.7/dist-packages/mopidy/mpd/protocol/status.py", line 274, in _status_time
    _status_time_total(futures) // 1000)
  File "/usr/local/lib/python2.7/dist-packages/mopidy/mpd/protocol/status.py", line 285, in _status_time_total
    elif current_tl_track.track.length is None:
AttributeError: 'Ref' object has no attribute 'length'
```

I'm using mopidy.js and error reported in browser console looks:
```
code: -32602
message: "Only Track objects can be added to the history"
traceback: "Traceback (most recent call last):↵  File "/usr/local/lib/python2.7/dist-packages/mopidy/utils/jsonrpc.py", line 132, in _handle_single_request↵    result = self._unwrap_result(result)↵  File "/usr/local/lib/python2.7/dist-packages/mopidy/utils/jsonrpc.py", line 221, in _unwrap_result↵    result = result.get()↵  File "/usr/lib/python2.7/dist-packages/pykka/future.py", line 299, in get↵    exec('raise exc_info[0], exc_info[1], exc_info[2]')↵  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 200, in _actor_loop↵    response = self._handle_receive(message)↵  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 294, in _handle_receive↵    return callee(*message['args'], **message['kwargs'])↵  File "/usr/local/lib/python2.7/dist-packages/mopidy/core/playback.py", line 277, in play↵    self._play(tl_track, on_error_step=1)↵  File "/usr/local/lib/python2.7/dist-packages/mopidy/core/playback.py", line 321, in _play↵    self.core.history._add_track(tl_track.track)↵  File "/usr/local/lib/python2.7/dist-packages/mopidy/core/history.py", line 27, in _add_track↵    raise TypeError('Only Track objects can be added to the history')↵TypeError: Only Track objects can be added to the history↵"type: "TypeError"
```

**Comment by szuniverse** [comment]
Hi!. After that what will be? Will the track start playing?

**Comment by morgoth** [comment]
Yes, it's playing, but the error is thrown on backend as well as on frontend

**Comment by morgoth** [comment]
Actually I just noticed that after playing one song and switching to next local track another error is thrown:
```
2015-04-01 20:58:45,361 ERROR [30285:Core-9] pykka: Unhandled exception in Core (urn:uuid:a7fa53b7-29a9-49c4-9fae-b994a87554b5):
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 200, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 294, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/local/lib/python2.7/dist-packages/mopidy/listener.py", line 49, in on_event
    getattr(self, event)(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mopidy/core/actor.py", line 87, in reached_end_of_stream
    self.playback._on_end_of_track()
  File "/usr/local/lib/python2.7/dist-packages/mopidy/core/playback.py", line 217, in _on_end_of_track
    self._change_track(next_tl_track)
  File "/usr/local/lib/python2.7/dist-packages/mopidy/core/playback.py", line 199, in _change_track
    self._play(on_error_step=on_error_step)
  File "/usr/local/lib/python2.7/dist-packages/mopidy/core/playback.py", line 321, in _play
    self.core.history._add_track(tl_track.track)
  File "/usr/local/lib/python2.7/dist-packages/mopidy/core/history.py", line 27, in _add_track
    raise TypeError('Only Track objects can be added to the history')
TypeError: Only Track objects can be added to the history
```

The client when tries to connect throws: 
```
message: "Core (urn:uuid:a7fa53b7-29a9-49c4-9fae-b994a87554b5) not found"
traceback: "Traceback (most recent call last):↵  File "/usr/local/lib/python2.7/dist-packages/mopidy/utils/jsonrpc.py", line 132, in _handle_single_request↵    result = self._unwrap_result(result)↵  File "/usr/local/lib/python2.7/dist-packages/mopidy/utils/jsonrpc.py", line 221, in _unwrap_result↵    result = result.get()↵  File "/usr/lib/python2.7/dist-packages/pykka/future.py", line 299, in get↵    exec('raise exc_info[0], exc_info[1], exc_info[2]')↵  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 470, in ask↵    self.tell(message)↵  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 437, in tell↵    raise _ActorDeadError('%s not found' % self)↵ActorDeadError: Core (urn:uuid:a7fa53b7-29a9-49c4-9fae-b994a87554b5) not found↵"
type: "ActorDeadError"
```
And when song stops playing, I need to restart Mopidy since its unusable

**Comment by morgoth** [comment]
I found a solution to this issue (kind of). Previously I was adding local tracks to queue by `tracklist.add` function with `tl_tracks` param, where tracks were simple objects with name and uri only attributes.
Now I'm adding them with `uris` param, which makes a lookup before, so all metadata info is properly added (altogether with length).
This also partially solves issues with https://discuss.mopidy.com/t/no-metadata-in-tracks-from-local-backend/654/7

**Comment by adamcik** [comment]
#865 and #700 already address issue. With these in place we'll be doing a lot more error checking, and providing early feedback for the cases where people use the API "wrong". Longer term the plan is to simplify the API so using it correctly isn't a challenge as it is now.

**Comment by tkem** [comment]
Since input and output parameters/types of Mopidy's API methods are IMHO
reasonably documented (sure, docs could *always* be improved), the
"challenge" here is actually to sit down and read the documentation, or
what?
