### ISSUE TITLE
AssertionError: D-Bus connection does not have a Connection instance associated with it

### ISSUE THREAD

**Issue by ronilaukkarinen** [mopidy/mopidy#1277]
Hello. Starting mopidy for the first time on Fedora 22. Can't connect to [moped](https://github.com/martijnboland/moped/) or any web interface.

````
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mopidy/internal/network.py", line 94, in handle_connection
    sock, addr = self.accept_connection()
  File "/usr/lib/python2.7/site-packages/mopidy/internal/network.py", line 106, in accept_connection
    return self.server_socket.accept()
  File "/usr/lib64/python2.7/socket.py", line 207, in accept
    return _socketobject(_sock=sock), addr
  File "/usr/lib64/python2.7/socket.py", line 193, in __init__
    for method in _delegate_methods:
  File "/usr/lib64/python2.7/site-packages/dbus/connection.py", line 534, in _signal_func
    signal_name):
  File "/usr/lib64/python2.7/site-packages/dbus/connection.py", line 443, in _iter_easy_matches
    for path in path_keys:
AssertionError: D-Bus connection does not have a Connection instance associated with it
````

**Comment by ronilaukkarinen** [comment]
Hmm the problem solved itself, still installing and updating some packages. I still get this when opening Google Chrome in http://192.168.2.100:6680/

````
This webpage is not available

ERR_CONNECTION_REFUSED
````

Any newbie tips?

**Comment by kingosticks** [comment]
Did you set the `http/hostname` option as per https://docs.mopidy.com/en/latest/ext/http/? If it doesn't look like this problem is an actual bug in Mopidy then we should continue this at http://discuss.mopidy.com.

**Comment by ronilaukkarinen** [comment]
Oh, thank you! Missed that one. It works now.
