### ISSUE TITLE
Receive the following error when trying to run mopidy.

### ISSUE THREAD

**Issue by lukeforrest** [mopidy/mopidy#1292]
Traceback (most recent call last):
  File "/usr/bin/mopidy", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3084, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3070, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3097, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 653, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 666, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 839, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'requests>=2.0' distribution was not found and is required by Mopidy

**Comment by jodal** [comment]
You're probably installing packages built for jessie (stable) on wheezy (oldstable). Luckily, the apt.mopidy.com server has mopidy packages built for both jessie and wheezy.

1. Replace "stable" with "wheezy" in /etc/apt/sources.list.d/mopidy.list: `sudo sed -i -e 's/stable/wheezy/' /etc/apt/sources.list.d/mopidy.list`
2. Run `sudo apt-get update`
3. Run `sudo apt-get upgrade`

**Comment by lukeforrest** [comment]
Still receiving the same error

**Comment by lukeforrest** [comment]
Got it working now.

**Comment by malteee** [comment]
Got the same error (#1307).

I tried the solution, @jodal mentioned in his comment, but it didnt work. I uninstall mopidy, put the following lines into my /etc/apt/sources.list.d/mopidy.list file:
```
deb http://apt.mopidy.com/ wheezy main contrib non-free
deb-src http://apt.mopidy.com/ wheezy main contrib non-free
```
made ```sudo sed -i -e 's/stable/wheezy/' /etc/apt/sources.list.d/mopidy.list``` and  ```sudo apt-get update``` and ```sudo apt-get upgrade``` and tried to reinstall it with ```sudo apt-get install mopidy```, but I get the same error again, when I try to run mopidy:
```
Traceback (most recent call last):
  File "/usr/bin/mopidy", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2711, in <module>
    parse_requirements(__requires__), Environment()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: requests>=2.0
```

I am using a raspberry pi, following these tutorial: http://geeks.noeit.com/turn-your-raspberry-pi-into-a-spotify-server/

**Comment by kingosticks** [comment]
As this is not a bug in mopidy, please can we continue this at
discuss.mopidy.com?

Be sure to remove any Mopidy lines from /etc/apt/sources.list file if you
added them when originally following that guide. In general, you'll find
more accurate instructions at docs.mopidy.com.

Got the same error (#1307 <https://github.com/mopidy/mopidy/issues/1307>).

I tried the solution, @jodal <https://github.com/jodal> mentioned in his
comment, but it didnt work. I uninstall mopidy, put the following lines
into my /etc/apt/sources.list.d/mopidy.list file:

deb http://apt.mopidy.com/ wheezy main contrib non-free
deb-src http://apt.mopidy.com/ wheezy main contrib non-free

made sudo sed -i -e 's/stable/wheezy/' /etc/apt/sources.list.d/mopidy.list
and sudo apt-get update and sudo apt-get upgrade and tried to reinstall it
with sudo apt-get install mopidy, but I get the same error again, when I
try to run mopidy:

Traceback (most recent call last):
  File "/usr/bin/mopidy", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2711,
in <module>
    parse_requirements(__requires__), Environment()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: requests>=2.0

I am using a raspberry pi, following these tutorial:
http://geeks.noeit.com/turn-your-raspberry-pi-into-a-spotify-server/

—
Reply to this email directly or view it on GitHub
<https://github.com/mopidy/mopidy/issues/1292#issuecomment-146641997>.
