### ISSUE TITLE
Scanning local media fails: ERROR    'int' object has no attribute 'load'

### ISSUE THREAD

**Issue by vasyugan** [mopidy/mopidy#1298]
mopidy running on a raspberrypi 1b with Raspbian Jessie. The media directory is mounted via NFS from another raspberrypi. Here is the console output:

Running "/usr/bin/mopidy --config /usr/share/mopidy/conf.d:/etc/mopidy/mopidy.conf local scan" as user mopidy

```
INFO     Starting Mopidy 1.1.1
INFO     Loading config from builtin defaults
INFO     Loading config from /etc/mopidy/mopidy.conf
INFO     Loading config from command line options
INFO     Enabled extensions: mpd, http, stream, podcast-gpodder, m3u, podcast-itunes, softwaremixer, file, musicbox_webclient, podcast, local, tunein, soundcloud
INFO     Disabled extensions: none
WARNING  Local library images not found
INFO     Found 8597 files in media_dir.
ERROR    'int' object has no attribute 'load'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mopidy/__main__.py", line 158, in main
    return args.command.run(args, proxied_config)
  File "/usr/lib/python2.7/dist-packages/mopidy/local/commands.py", line 91, in run
    num_tracks = library.load()
AttributeError: 'int' object has no attribute 'load'
Traceback (most recent call last):
  File "/usr/bin/mopidy", line 9, in <module>
    load_entry_point('Mopidy==1.1.1', 'console_scripts', 'mopidy')()
  File "/usr/lib/python2.7/dist-packages/mopidy/__main__.py", line 158, in main
    return args.command.run(args, proxied_config)
  File "/usr/lib/python2.7/dist-packages/mopidy/local/commands.py", line 91, in run
    num_tracks = library.load()
AttributeError: 'int' object has no attribute 'load'
```

**Comment by adamcik** [comment]
```WARNING  Local library images not found`` is the key line, seems we crash like this when we are configured to use a local library provider that does not exists / isn't installed.

**Comment by adamcik** [comment]
So to workaround this make sure `mopidy-local-images` is installed, and/or configure and installed library provider.

To reproduce simply run: `mopidy -o local/library=foo local scan`

**Comment by vasyugan** [comment]
sorry. My bad. I re-used the old config without reinstalling all components

**Comment by kdelwat** [comment]
I'd like to take a shot at catching this error if that sounds alright.

**Comment by adamcik** [comment]
Feel free :-)
