### ISSUE TITLE
No module named gobject

### ISSUE THREAD

**Issue by hostman89** [mopidy/mopidy#1313]
hello, I get not find the solution to this problem. I install mopidy says documentacion. I installed pip install Mopidy-Spotify or any extension pip and mopidy using stops working.

root@raspberrypi:/home/pi# mopidy

ERROR: The gobject Python package was not found.

Mopidy requires GStreamer (and GObject) to work. These are C libraries
with a number of dependencies themselves, and cannot be installed with
the regular Python tools like pip.

Please see http://docs.mopidy.com/en/latest/installation/ for
instructions on how to install the required dependencies.

Traceback (most recent call last):
  File "/usr/local/bin/mopidy", line 9, in <module>
    load_entry_point('Mopidy==1.1.1', 'console_scripts', 'mopidy')()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line                                                                                                                                                       558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line                                                                                                                                                       2682, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line                                                                                                                                                       2355, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line                                                                                                                                                       2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/site-packages/Mopidy-1.1.1-py2.7.egg/mopidy/__m                                                                                                                                                      ain__.py", line 10, in <module>
    import gobject   # noqa
ImportError: No module named gobject

I tried to install gobject  and GStreamer package but without result.
Sorry for my English. Thank you.

**Comment by adamcik** [comment]
If this is a standard Debian based raspi install I would strongly recommend starting from scratch and just following https://docs.mopidy.com/en/latest/installation/debian/ and pulling in Mopidy-Spotify via aptitude.

Based on the info you've provided, I would guess that you could have ended up with state were you have virtualenv for parts of the system as it can't find any of the gobject bits and pieces.

**Comment by adamcik** [comment]
Closing as this hasn't gotten any follow up, for future support requests please use https://discuss.mopidy.com/ :-)
