### ISSUE TITLE
Playlist from Spotify does not show up

### ISSUE THREAD

**Issue by vdbee** [mopidy/mopidy#1324]
It looks like that an error occurs in Mopidy when it tries to load playlists. This error appears to be Spotify-account dependent. I am not suffering this error, but my father does. I think the error I now encouter is different as those that I found on the web. I believe so because now the Mopidy log shows an error while it did not do that in the past for similar errors.

I pasted a part of my log below:

```
2015-10-31 20:00:02,687 INFO [210:MainThread] mopidy.__main__: Starting Mopidy 1.1.1
2015-10-31 20:00:03,998 INFO [210:MainThread] mopidy.config: Loading config from builtin defaults
2015-10-31 20:00:04,015 INFO [210:MainThread] mopidy.config: Loading config from /etc/mopidy/mopidy.conf
2015-10-31 20:00:04,031 INFO [210:MainThread] mopidy.config: Loading config from command line options
2015-10-31 20:00:04,218 INFO [210:MainThread] mopidy.__main__: Enabled extensions: mopify, spotify, mpd, http, stream, m3u, youtube, softwaremixer, file, musicbox_webclient, webse$
2015-10-31 20:00:04,220 INFO [210:MainThread] mopidy.__main__: Disabled extensions: local
2015-10-31 20:00:06,547 INFO [210:MainThread] mopify: Setup Mopify
2015-10-31 20:00:07,758 INFO [210:MainThread] mopidy.commands: Starting Mopidy mixer: SoftwareMixer
2015-10-31 20:00:07,767 INFO [210:MainThread] mopidy.commands: Mixer volume set to 95
2015-10-31 20:00:07,769 INFO [210:MainThread] mopidy.commands: Starting Mopidy audio
2015-10-31 20:00:07,778 INFO [210:MainThread] mopidy.commands: Starting Mopidy backends: TuneInBackend, YouTubeBackend, SpotifyBackend, StreamBackend, M3UBackend, FileBackend
2015-10-31 20:00:07,884 INFO [210:MainThread] mopidy.m3u.playlists: Loaded 0 M3U playlists from /music
2015-10-31 20:00:07,989 INFO [210:Audio-2] mopidy.audio.actor: Audio output set to "alsasink"
2015-10-31 20:00:08,524 INFO [210:MainThread] mopidy.commands: Starting Mopidy core
2015-10-31 20:00:09,456 INFO [210:SpotifyEventLoop] spotify.session: Spotify logged in
2015-10-31 20:00:09,458 INFO [210:SpotifyEventLoop] mopidy_spotify.backend: Logged in to Spotify in offline mode
2015-10-31 20:00:10,007 INFO [210:SpotifyEventLoop] mopidy_spotify.backend: Logged in to Spotify in online mode
2015-10-31 20:00:20,015 ERROR [210:MainThread] mopidy.core.playlists: SpotifyBackend backend caused an exception.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mopidy/core/playlists.py", line 18, in _backend_error_handling
    yield
  File "/usr/lib/python2.7/dist-packages/mopidy/core/playlists.py", line 56, in as_list
    playlists = future.get()
  File "/usr/lib/python2.7/dist-packages/pykka/threading.py", line 52, in get
    compat.reraise(*self._data['exc_info'])
  File "/usr/lib/python2.7/dist-packages/pykka/compat.py", line 12, in reraise
    exec('raise tp, value, tb')
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 201, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 295, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/lib/python2.7/dist-packages/mopidy_spotify/playlists.py", line 23, in as_list
    list(self._get_starred_playlist_ref()) +
  File "/usr/lib/python2.7/dist-packages/mopidy_spotify/playlists.py", line 37, in _get_starred_playlist_ref
    sp_starred.load()
  File "/usr/lib/python2.7/dist-packages/spotify/playlist.py", line 118, in load
    return utils.load(self._session, self, timeout=timeout)
  File "/usr/lib/python2.7/dist-packages/spotify/utils.py", line 246, in load
    raise spotify.Timeout(timeout)
Timeout: Operation did not complete in 10.000s
2015-10-31 20:00:20,043 INFO [210:MainThread] mopidy.commands: Starting Mopidy frontends: QueueManagerFrontend, MpdFrontend, HttpFrontend
2015-10-31 20:00:20,058 INFO [210:MainThread] mopidy.mpd.actor: MPD server running at [::ffff:127.0.0.1]:6600
2015-10-31 20:00:20,072 INFO [210:HttpFrontend-15] mopidy.http.actor: HTTP server running at [::]:6680
2015-10-31 20:00:26,950 INFO [210:MpdSession-16] mopidy.mpd.session: New MPD connection from [::ffff:127.0.0.1]:47648
2015-10-31 20:00:36,900 ERROR [210:HttpServer] mopidy.core.playlists: SpotifyBackend backend caused an exception.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mopidy/core/playlists.py", line 18, in _backend_error_handling
    yield
  File "/usr/lib/python2.7/dist-packages/mopidy/core/playlists.py", line 56, in as_list
    playlists = future.get()
```

**Comment by jodal** [comment]
`SpotifyBackend backend caused an exception.` indicates that this is a Mopidy-Spotify issue and really belongs at https://github.com/mopidy/mopidy-spotify/issues. Too bad GitHub doesn't support moving issues to another repo.

From the log I can say that you managed to log into Spotify, but then a request for all the Spotify playlists (`as_list`) immediately after login timed out after trying to get the starred playlist for 10 seconds.

The second stack trace is cut off after two frames, so I don't know what happened there.

**Comment by vdbee** [comment]
Thanks, I'll move this issue.


Groet, Rens





On Mon, Nov 2, 2015 at 2:10 PM -0800, "Stein Magnus Jodal" <notifications@github.com> wrote:
`SpotifyBackend backend caused an exception.` indicates that this is a Mopidy-Spotify issue and really belongs at https://github.com/mopidy/mopidy-spotify/issues. Too bad GitHub doesn't support moving issues to another repo.

From the log I can say that you managed to log into Spotify, but then a request for all the Spotify playlists (`as_list`) immediately after login timed out after trying to get the starred playlist for 10 seconds.

The second stack trace is cut off after two frames, so I don't know what happened there.

---
