### ISSUE TITLE
dbus exception in zeroconf code

### ISSUE THREAD

**Issue by adamcik** [mopidy/mopidy#1363]
We should catch this in such a way that we don't get a traceback.

```
2015-12-17 22:34:24,819 ERROR    [HttpFrontend-11] /home/adamcik/dev/mopidy-virtualenv/local/lib/python2.7/site-packages/pykka/actor.py:269
  pykka Unhandled exception in HttpFrontend (urn:uuid:1459add8-906e-49ee-a267-6068e2cbd4f1):
Traceback (most recent call last):
  File "/home/adamcik/dev/mopidy-virtualenv/local/lib/python2.7/site-packages/pykka/actor.py", line 192, in _actor_loop
    self.on_start()
  File "/home/adamcik/dev/mopidy/mopidy/http/actor.py", line 62, in on_start
    port=self.port)
  File "/home/adamcik/dev/mopidy/mopidy/zeroconf.py", line 66, in __init__
    self.display_hostname = '%s' % self.server.GetHostName()
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
```

**Comment by jodal** [comment]
The bad code was added by me after the release of 1.1 and fixed by @bbenne10 in 128de6cd015ecdc6c44c9c209484e436b2dab31c. Thus, changing milestone and closing.
