### ISSUE TITLE
dbus: zeroconf traceback

### ISSUE THREAD

**Issue by adamcik** [mopidy/mopidy#1424]
Don't know if I can reproduce, or what I've done wrong, but this kinda half way breaks the HTTP actor. I can use frontends, but events never get sent out. Happened in 1.1.2-289-g4e39f09, i.e. latest develop.

```
2016-02-03 21:41:41,389 ERROR    [HttpFrontend-14] /usr/lib/python2.7/dist-packages/dbus/connection.py:646
  dbus.connection Unable to set arguments (-1, -1, dbus.UInt32(0L), None, u'_mopidy-http._tcp', u'', u'', dbus.UInt16(6680), dbus.Array([], signature=dbus.Signature('ay'))) according to signature u'iiussssqaay': <type 'exceptions.TypeError'>: Expected a string or unicode object
2016-02-03 21:41:41,389 ERROR    [HttpFrontend-14] /home/adamcik/dev/mopidy-virtualenv/local/lib/python2.7/site-packages/pykka/actor.py:269
  pykka Unhandled exception in HttpFrontend (urn:uuid:6385a0b5-8e60-40de-80ba-99c846090a49):
Traceback (most recent call last):
  File "/home/adamcik/dev/mopidy-virtualenv/local/lib/python2.7/site-packages/pykka/actor.py", line 192, in _actor_loop
    self.on_start()
  File "/home/adamcik/dev/mopidy/mopidy/http/actor.py", line 68, in on_start
    self.zeroconf_mopidy_http.publish()
  File "/home/adamcik/dev/mopidy/mopidy/zeroconf.py", line 116, in publish
    _convert_text_list_to_dbus_format(self.text))
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 641, in call_blocking
    message.append(signature=signature, *args)
TypeError: Expected a string or unicode object
```

**Comment by 5AMsan** [comment]
I have this error with fresh dev environment setup on RPI3 Raspian. I used the [docs](https://docs.mopidy.com/en/latest/devenv/#make-a-development-workspace) to setup my dev env.
`INFO     Starting GLib mainloop
ERROR    Unable to set arguments (-1, -1, dbus.UInt32(0L), None, u'_http._tcp', u'', u'', dbus.UInt16(6680), dbus.Array([], signature=dbus.Signature('ay'))) according to signature u'iiussssqaay': <type 'exceptions.TypeError'>: Expected a string or unicode object
ERROR    Unhandled exception in HttpFrontend (urn:uuid:30444e24-70ca-42c0-9ba3-6c6545caa413):
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 192, in _actor_loop
    self.on_start()
  File "/home/pi/mopidy-dev/mopidy/mopidy/http/actor.py", line 67, in on_start
    self.zeroconf_http.publish()
  File "/home/pi/mopidy-dev/mopidy/mopidy/zeroconf.py", line 116, in publish
    _convert_text_list_to_dbus_format(self.text))
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 641, in call_blocking
    message.append(signature=signature, *args)
TypeError: Expected a string or unicode object`

I'll try to install from scratch once more.
