### ISSUE TITLE
Sorting in ncmpcpp working very slow and unstable (may be only with Spotify backend)

### ISSUE THREAD

**Issue by actionless** [mopidy/mopidy#1468]
steps to reproduce:
0) open `ncmpcpp`
1) add few hundreds songs from spotify to main playlist
2) sort main playlist (Ctrl+S)

Mopidy responds slower and after some time throws the exception:

``` py
ERROR    Unhandled exception in MpdFrontend (urn:uuid:9b5696c9-0261-4eea-8132-f43b1017f286):
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 200, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 294, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/lib/python2.7/site-packages/mopidy/mpd/actor.py", line 84, in on_event
    self.send_idle(_CORE_EVENTS_TO_IDLE_SUBSYSTEMS[event])
  File "/usr/lib/python2.7/site-packages/mopidy/mpd/actor.py", line 88, in send_idle
    listener.send(session.MpdSession, subsystem)
  File "/usr/lib/python2.7/site-packages/mopidy/listener.py", line 27, in send
    'kwargs': kwargs,
  File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 437, in tell
    raise _ActorDeadError('%s not found' % self)
ActorDeadError: MpdSession (urn:uuid:4c427b21-ab0b-426d-b795-efb9afb46db0) not found
```

UPD: forgot to mention what i am using release 2.0.0

**Comment by kingosticks** [comment]
What is mb?

**Comment by actionless** [comment]
may be

**Comment by adamcik** [comment]
`ActorDeadError` is just telling us that something killed that thread previously. Do you happen to have any errors or the like earlier in the logs?

**Comment by trygveaa** [comment]
@adamcik: I can easily reproduce this. It doesn't say anything earlier in the log.

**Comment by adamcik** [comment]
I can't seem to easily reproduce this.

**Comment by actionless** [comment]
since DBus in spotify is fixed already i am not more using mopidy so feel free to close this

**Comment by jodal** [comment]
Closing as there's nothing to go on here and the original poster has moved on.

**Comment by trygveaa** [comment]
I can still reproduce this consistently, however only on one of my machines. It also happens randomly from time to time on that machine.

Do you have any suggestions on how to debug this?

**Comment by makkanx** [comment]
Any news on this issue? I keep getting it many times every day.

**Comment by kingosticks** [comment]
If you can easily and reliably reproduce it then a *debug* log showing the exact chain of events that causes this.

**Comment by actionless** [comment]
> And can you determine if it is only when the playlist contains Spotify tracks, that was never made clear in the original report.

yeah, it was only with Spotify, never with local tracks

**Comment by makkanx** [comment]
I'm running with save-debug-log right now. My current playlist has both local and spotify tracks and a total of 1568 tracks.

**Comment by makkanx** [comment]
Here is a link to debug log, deps and config.
[https://gist.github.com/makkanx/244277b5c4cd67d8a587a99399a6be07]

**Comment by makkanx** [comment]
I got the same error without spotify tracks.
(https://gist.github.com/makkanx/28c5ac01eac3e62039c8f2792e8f267e)
I have the complete logfile incase needed.
This playlist has 1465 tracks.

**Comment by kingosticks** [comment]
The OP was confident this was only with Spotify tracks so is this actually the same issue?

Is your issue still something to do with sorting? I don't see any reordering MPD commands in those logs. There's not much of anything going on. Did nothing happen before the snippet you provided? It might be better to provide the entire log. And to *disable* all extensions except local.

**Comment by makkanx** [comment]
Mine happens even if I don't sort.

**Comment by kingosticks** [comment]
OK so doesn't sound like same issue as the OP. And not necessarily the same as #1750. Can you provide steps for us to reproduce and a full debug log in a new issue. Reusing this one will just be confusing.

**Comment by makkanx** [comment]
It is difficult to reproduce but it happens quite often if I have Spotify songs. Right now I'm running with only m3u, files and mpd enabled to see if it happens then.

**Comment by jodal** [comment]
> *This was generated by AI during triage.*

The original reporter no longer uses Mopidy, and the later reports describe a different problem. The MPD frontend is now in Mopidy-MPD. If sorting large playlists still fails, please open an issue at https://github.com/mopidy/mopidy-mpd/issues with a debug log. Closing.
