### ISSUE TITLE
Weird error logging

### ISSUE THREAD

**Issue by camilonova** [mopidy/mopidy#1526]
I was trying to play this stream:

    http://www.977music.com/itunes/classicrock.pls

And I was getting this error:

```
2016-06-11 21:13:56,724 INFO [1519:StreamBackend-4] urllib3.connectionpool: Starting new HTTP connection (1): 7609.live.streamtheworld.com
2016-06-11 21:14:08,459 WARNING [1519:StreamBackend-4] mopidy.internal.http: Download of 'http://7609.live.streamtheworld.com:80/977_CLASSROCKAAC_SC' failed due to download taking more than 4.985s
2016-06-11 21:14:08,471 INFO [1519:StreamBackend-4] mopidy.stream.actor: Unwrapping stream from URI (http://www.977music.com/itunes/classicrock.pls) failed: error downloading URI http://7609.live.streamtheworld.com:80/977_CLASSROCKAAC_SC
2016-06-11 21:14:08,537 INFO [1519:HttpServer] tornado.access: 200 POST /mopidy/rpc (45.79.148.19) 27188.75ms
2016-06-11 21:14:14,364 INFO [1519:HttpServer] tornado.access: 200 POST /mopidy/rpc (45.79.148.19) 5597.62ms
2016-06-11 21:14:19,953 WARNING [1519:MainThread] mopidy.audio.actor: Could not find a text/html decoder to handle media.
2016-06-11 21:14:19,963 WARNING [1519:MainThread] mopidy.audio.gst: GStreamer warning: gst-stream-error-quark: No decoder available for type 'text/html'. (6)
2016-06-11 21:14:19,972 ERROR [1519:MainThread] mopidy.audio.gst: GStreamer error: gst-core-error-quark: Your GStreamer installation is missing a plug-in. (12)
```

But I played changing the timeout setting on the configuration file adding:

```
[stream]
timeout = 10000
```

Before I had nothing, and after adding the timeout setting is working.

I spent a lot of time installing and uninstalling Gstreamer. The error message from the timeout should be better.

I started changing the timeout setting after seeing this file: https://github.com/mopidy/mopidy/blob/20ba1fd90e81939a0da8a543d3e8bbb8472e9765/mopidy/internal/http.py#L28

**Comment by PanderMusubi** [comment]
I have the same problem for M3U file

    $ cat /var/lib/mopidy/playlists/ifm2-128mp3.m3u 
    #EXTM3U
    #EXTINF:-1,Intergalactic FM Classix (128k MP3)
    http://radio.intergalacticfm.com/2

I get

    2016-06-18 20:52:17,133 WARNING [12519:MainThread] mopidy.audio.actor: Could not find a text/uri-list decoder to handle media.
    2016-06-18 20:52:17,153 WARNING [12519:MainThread] mopidy.audio.gst: GStreamer warning: gst-stream-error-quark: No decoder available for type 'text/uri-list'. (6)
    2016-06-18 20:52:17,160 ERROR [12519:MainThread] mopidy.audio.gst: GStreamer error: gst-core-error-quark: Your GStreamer installation is missing a plug-in. (12)

while having installed

$ dpkg -l|grep gst|awk '{print $2}'
gir1.2-gst-plugins-base-1.0
gir1.2-gstreamer-1.0
gstreamer1.0-alsa:armhf
gstreamer1.0-plugins-bad:armhf
gstreamer1.0-plugins-base:armhf
gstreamer1.0-plugins-good:armhf
gstreamer1.0-plugins-ugly:armhf
gstreamer1.0-pulseaudio:armhf
gstreamer1.0-tools
gstreamer1.0-x:armhf
libgstreamer-plugins-bad1.0-0:armhf
libgstreamer-plugins-base1.0-0:armhf
libgstreamer1.0-0:armhf
python-gst-1.0

for PLS file

$ cat /var/lib/mopidy/playlists/ifm2-128mp3.pls 
[playlist]
numberofentries=1
File1=http://radio.intergalacticfm.com/2
Title1=Intergalactic FM Classix (128k MP3)
Length1=-1
Version=2
    

I get

    2016-06-18 20:53:58,824 ERROR [12519:MainThread] mopidy.audio.gst: GStreamer error: gst-stream-error-quark: This appears to be a text file (5)

**Comment by PanderMusubi** [comment]
Changing the timeout had no affect for me. Any other workarounds that I could try?

**Comment by adamcik** [comment]
As far as our code is concerned this is an invalid playlist with `length=-1`. Not sure what is really correct for PLS files, but we should probably just ignore it when we come across it and treat it like no length given.

```
2016-06-19 23:11:13,360 ERROR    [Core-11] /home/adamcik/dev/mopidy/mopidy/core/library.py:27
  mopidy.core.library StreamBackend backend caused an exception.
Traceback (most recent call last):
  File "/home/adamcik/dev/mopidy/mopidy/core/library.py", line 19, in _backend_error_handling
    yield
  File "/home/adamcik/dev/mopidy/mopidy/core/library.py", line 236, in lookup
    result = future.get()
  File "/home/adamcik/dev/mopidy-virtualenv/local/lib/python2.7/site-packages/pykka/threading.py", line 52, in get
    compat.reraise(*self._data['exc_info'])
  File "/home/adamcik/dev/mopidy-virtualenv/local/lib/python2.7/site-packages/pykka/compat.py", line 12, in reraise
    exec('raise tp, value, tb')
  File "/home/adamcik/dev/mopidy-virtualenv/local/lib/python2.7/site-packages/pykka/actor.py", line 201, in _actor_loop
    response = self._handle_receive(message)
  File "/home/adamcik/dev/mopidy-virtualenv/local/lib/python2.7/site-packages/pykka/actor.py", line 295, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/home/adamcik/dev/mopidy/mopidy/stream/actor.py", line 69, in lookup
    uri=uri, length=scan_result.duration)
  File "/home/adamcik/dev/mopidy/mopidy/models/immutable.py", line 214, in replace
    other = super(ValidatedImmutableObject, self).replace(**kwargs)
  File "/home/adamcik/dev/mopidy/mopidy/models/immutable.py", line 116, in replace
    other._set_field(key, value)
  File "/home/adamcik/dev/mopidy/mopidy/models/immutable.py", line 186, in _set_field
    object.__setattr__(self, name, value)
  File "/home/adamcik/dev/mopidy/mopidy/models/fields.py", line 50, in __set__
    value = self.validate(value)
  File "/home/adamcik/dev/mopidy/mopidy/models/fields.py", line 131, in validate
    (self._name, self._min, value))
ValueError: Expected length to be at least 0, not -1
```

**Comment by adamcik** [comment]
http://7609.live.streamtheworld.com:80/977_CLASSROCKAAC_SC gives a duration of -1 for some reason, so this is in our scanner code.

**Comment by adamcik** [comment]
Following should probably fix this what I'm seeing with http://www.977music.com/itunes/classicrock.pls and tested with http://radio.intergalacticfm.com/2 as well.

```
diff --git a/mopidy/audio/scan.py b/mopidy/audio/scan.py
index 2788863..92acc8c 100644
--- a/mopidy/audio/scan.py
+++ b/mopidy/audio/scan.py
@@ -68,6 +68,9 @@ class Scanner(object):
             pipeline.set_state(Gst.State.NULL)
             del pipeline
 
+        if duration < 0:
+            duration = None
+
         return _Result(uri, tags, duration, seekable, mime, have_audio)
```

**Comment by PanderMusubi** [comment]
Still problem. Can play streams from mopidy-somafm and mopidy-dirble but not these playlist files:

    # ls -l /var/lib/mopidy/playlists/
    total 8
    -rw-r--r-- 1 mopidy audio  86 Jun 20 10:05 ifm2-128mp3.m3u
    -rw-r--r-- 1 mopidy audio 130 Jun 20 10:05 ifm2-128mp3.pls

with contents:

    # more /var/lib/mopidy/playlists/*
    ::::::::::::::
    /var/lib/mopidy/playlists/ifm2-128mp3.m3u
    ::::::::::::::
    #EXTM3U
    #EXTINF:-1,Intergalactic FM - Disco Fetish
    http://radio.intergalacticfm.com/2
    ::::::::::::::
    /var/lib/mopidy/playlists/ifm2-128mp3.pls
    ::::::::::::::
    [playlist]
    numberofentries=1
    File1=http://radio.intergalacticfm.com/2
    Title1=Intergalactic FM - Disco Fetish
    Length1=-1
    Version=2

installed:

    # dpkg -l|grep mopidy|awk {'print $2" "$3}'
    mopidy 2.0.0-1
    mopidy-dirble 1.3.0-1
    mopidy-somafm 1.0.1-1
    mopidy-youtube 2.0.0-2
    # dpkg -l|grep gst|awk {'print $2" "$3}'
    gir1.2-gst-plugins-base-1.0 1.4.4-2
    gir1.2-gstreamer-1.0 1.4.4-2
    gstreamer1.0-alsa:armhf 1.4.4-2
    gstreamer1.0-plugins-bad:armhf 1.4.4-2.1rpi4rpi1g
    gstreamer1.0-plugins-base:armhf 1.4.4-2
    gstreamer1.0-plugins-good:armhf 1.4.4-2
    gstreamer1.0-plugins-ugly:armhf 1.4.4-2
    gstreamer1.0-pulseaudio:armhf 1.4.4-2
    gstreamer1.0-tools 1.4.4-2
    gstreamer1.0-x:armhf 1.4.4-2
    libgstreamer-plugins-bad1.0-0:armhf 1.4.4-2.1rpi4rpi1g
    libgstreamer-plugins-base1.0-0:armhf 1.4.4-2
    libgstreamer1.0-0:armhf 1.4.4-2
    python-gst-1.0 1.2.1-1.1

and config:

    # cat /etc/mopidy/mopidy.conf 
    [core]
    cache_dir = /var/cache/mopidy
    config_dir = /etc/mopidy
    data_dir = /var/lib/mopidy
    
    [logging]
    config_file = /etc/mopidy/logging.conf
    debug_file = /var/log/mopidy/mopidy-debug.log
    
    [m3u]
    playlists_dir = /var/lib/mopidy/playlists
    
    [mpd]
    hostname = ::
    
    [http]
    hostname = ::
    
    [somafm]
    encoding = aac
    quality = highest
    
    [dirble]
    api_key = ******

These are the errors when playing either one of those playlist files, there is no sound and playing stops:
    2016-06-20 10:05:42,506 WARNING [3101:FileBackend-6] mopidy.file.library: Failed looking up file:///var/lib/mopidy/playlists/ifm2-128mp3.pls: gst-stream-error-quark: This appears to be a text file (5)
    2016-06-20 10:05:43,658 WARNING [3101:FileBackend-6] mopidy.file.library: Failed looking up file:///var/lib/mopidy/playlists/ifm2-128mp3.pls: gst-stream-error-quark: This appears to be a text file (5)
    2016-06-20 10:05:46,777 WARNING [3101:MainThread] mopidy.audio.actor: Could not find a text/uri-list decoder to handle media.
    2016-06-20 10:05:46,782 WARNING [3101:MainThread] mopidy.audio.gst: GStreamer warning: gst-stream-error-quark: No decoder available for type 'text/uri-list'. (6)
    2016-06-20 10:05:46,788 ERROR [3101:MainThread] mopidy.audio.gst: GStreamer error: gst-core-error-quark: Your GStreamer installation is missing a plug-in. (12)
    2016-06-20 10:06:01,768 WARNING [3101:FileBackend-6] mopidy.file.library: Failed looking up file:///var/lib/mopidy/playlists/ifm2-128mp3.pls: gst-stream-error-quark: This appears to be a text file (5)
    2016-06-20 10:06:01,882 ERROR [3101:MainThread] mopidy.audio.gst: GStreamer error: gst-stream-error-quark: This appears to be a text file (5)

**Comment by adamcik** [comment]
@PanderMusubi I susspect your issue is different from the main one we diagnosed here. It just boils down to the fact that the file backend doesn't handle playlist unwrapping now that we got rid of the magic "global" support for it we used to have.

We should start new bug to track that.

**Comment by PanderMusubi** [comment]
Yes, because this patch did fix the problem with mopidy-podcast but not with normal playlists with streams.
