### ISSUE TITLE
Error when trying to add stream via MPD client

### ISSUE THREAD

**Issue by Shellfishgene** [mopidy/mopidy#1557]
I activated the stream plugin and use GMPC to add a URL, however I get errors:
```
Aug 27 08:46:04 raspberrypi2 mopidy[13222]: INFO     New MPD connection from [::ffff:192.168.178.37]:63350
Aug 27 08:46:25 raspberrypi2 mopidy[13222]: ERROR    StreamBackend backend caused an exception.
Aug 27 08:46:25 raspberrypi2 mopidy[13222]: Traceback (most recent call last):
Aug 27 08:46:25 raspberrypi2 mopidy[13222]: File "/usr/lib/python2.7/dist-packages/mopidy/core/library.py", line 19, in _backend_error_handling
Aug 27 08:46:25 raspberrypi2 mopidy[13222]: yield
Aug 27 08:46:25 raspberrypi2 mopidy[13222]: File "/usr/lib/python2.7/dist-packages/mopidy/core/library.py", line 236, in lookup
Aug 27 08:46:25 raspberrypi2 mopidy[13222]: result = future.get()
Aug 27 08:46:25 raspberrypi2 mopidy[13222]: File "/usr/lib/python2.7/dist-packages/pykka/threading.py", line 52, in get
Aug 27 08:46:25 raspberrypi2 mopidy[13222]: compat.reraise(*self._data['exc_info'])
Aug 27 08:46:25 raspberrypi2 mopidy[13222]: File "/usr/lib/python2.7/dist-packages/pykka/compat.py", line 12, in reraise
Aug 27 08:46:25 raspberrypi2 mopidy[13222]: exec('raise tp, value, tb')
Aug 27 08:46:25 raspberrypi2 mopidy[13222]: File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 201, in _actor_loop
Aug 27 08:46:25 raspberrypi2 mopidy[13222]: response = self._handle_receive(message)
Aug 27 08:46:25 raspberrypi2 mopidy[13222]: File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 295, in _handle_receive
Aug 27 08:46:25 raspberrypi2 mopidy[13222]: return callee(*message['args'], **message['kwargs'])
Aug 27 08:46:25 raspberrypi2 mopidy[13222]: File "/usr/lib/python2.7/dist-packages/mopidy/stream/actor.py", line 69, in lookup
Aug 27 08:46:25 raspberrypi2 mopidy[13222]: uri=uri, length=scan_result.duration)
Aug 27 08:46:25 raspberrypi2 mopidy[13222]: File "/usr/lib/python2.7/dist-packages/mopidy/models/immutable.py", line 214, in replace
Aug 27 08:46:25 raspberrypi2 mopidy[13222]: other = super(ValidatedImmutableObject, self).replace(**kwargs)
Aug 27 08:46:25 raspberrypi2 mopidy[13222]: File "/usr/lib/python2.7/dist-packages/mopidy/models/immutable.py", line 116, in replace
Aug 27 08:46:25 raspberrypi2 mopidy[13222]: other._set_field(key, value)
Aug 27 08:46:25 raspberrypi2 mopidy[13222]: File "/usr/lib/python2.7/dist-packages/mopidy/models/immutable.py", line 186, in _set_field
Aug 27 08:46:25 raspberrypi2 mopidy[13222]: object.__setattr__(self, name, value)
Aug 27 08:46:25 raspberrypi2 mopidy[13222]: File "/usr/lib/python2.7/dist-packages/mopidy/models/fields.py", line 50, in __set__
Aug 27 08:46:25 raspberrypi2 mopidy[13222]: value = self.validate(value)
Aug 27 08:46:25 raspberrypi2 mopidy[13222]: File "/usr/lib/python2.7/dist-packages/mopidy/models/fields.py", line 131, in validate
Aug 27 08:46:25 raspberrypi2 mopidy[13222]: (self._name, self._min, value))
Aug 27 08:46:25 raspberrypi2 mopidy[13222]: ValueError: Expected length to be at least 0, not -1
```

**Comment by adamcik** [comment]
https://github.com/mopidy/mopidy/issues/1526#issuecomment-227020717 is the same issue. The fix was released in v2.0.1 (2016-08-16). Feel free to reopen if you can reproduce with 2.0.1
