### ISSUE TITLE
Crash on "reversing playlist" (ncmpcpp)

### ISSUE THREAD

**Issue by girst** [mopidy/mopidy#1610]
Whenever I use [https://pkgbuild.com/~jelle/ncmpcpp/l](`C-R`) to reverse the order of songs in the queue, mopidy crashes. 

`ncmpcpp` reorders the queue, then (on clicking on any song) complains, "MPD: no such song", and `mopidy` thows the error on the end of this issue. 

The only way of recovering is to kill and restart mopdiy. 

let me know if you need more info, or how else I could be of help, 

tobias

```
ERROR    Unhandled exception in MpdSession (urn:uuid:6c7c845d-3572-4a97-9055-698ef9b07a52):
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 201, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 304, in _handle_receive
    return self.on_receive(message)
  File "/usr/lib64/python2.7/site-packages/mopidy/internal/network.py", line 369, in on_receive
    self.on_line_received(line)
  File "/usr/lib64/python2.7/site-packages/mopidy/mpd/session.py", line 34, in on_line_received
    response = self.dispatcher.handle_request(line)
  File "/usr/lib64/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 47, in handle_request
    return self._call_next_filter(request, response, filter_chain)
  File "/usr/lib64/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 69, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/usr/lib64/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 77, in _catch_mpd_ack_errors_filter
    return self._call_next_filter(request, response, filter_chain)
  File "/usr/lib64/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 69, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/usr/lib64/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 87, in _authenticate_filter
    return self._call_next_filter(request, response, filter_chain)
  File "/usr/lib64/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 69, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/usr/lib64/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 106, in _command_list_filter
    response = self._call_next_filter(request, response, filter_chain)
  File "/usr/lib64/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 69, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/usr/lib64/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 135, in _idle_filter
    response = self._call_next_filter(request, response, filter_chain)
  File "/usr/lib64/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 69, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/usr/lib64/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 148, in _add_ok_filter
    response = self._call_next_filter(request, response, filter_chain)
  File "/usr/lib64/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 69, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/usr/lib64/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 160, in _call_handler_filter
    response = self._format_response(self._call_handler(request))
  File "/usr/lib64/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 175, in _call_handler
    return protocol.commands.call(tokens, context=self.context)
  File "/usr/lib64/python2.7/site-packages/mopidy/mpd/protocol/__init__.py", line 180, in call
    return self.handlers[tokens[0]](context, *tokens[1:])
  File "/usr/lib64/python2.7/site-packages/mopidy/mpd/protocol/__init__.py", line 158, in validate
    return func(**callargs)
  File "/usr/lib64/python2.7/site-packages/mopidy/mpd/protocol/command_list.py", line 42, in command_list_end
    command, current_command_list_index=index)
  File "/usr/lib64/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 47, in handle_request
    return self._call_next_filter(request, response, filter_chain)
  File "/usr/lib64/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 69, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/usr/lib64/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 77, in _catch_mpd_ack_errors_filter
    return self._call_next_filter(request, response, filter_chain)
  File "/usr/lib64/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 69, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/usr/lib64/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 87, in _authenticate_filter
    return self._call_next_filter(request, response, filter_chain)
  File "/usr/lib64/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 69, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/usr/lib64/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 106, in _command_list_filter
    response = self._call_next_filter(request, response, filter_chain)
  File "/usr/lib64/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 69, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/usr/lib64/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 135, in _idle_filter
    response = self._call_next_filter(request, response, filter_chain)
  File "/usr/lib64/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 69, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/usr/lib64/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 148, in _add_ok_filter
    response = self._call_next_filter(request, response, filter_chain)
  File "/usr/lib64/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 69, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/usr/lib64/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 160, in _call_handler_filter
    response = self._format_response(self._call_handler(request))
  File "/usr/lib64/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 175, in _call_handler
    return protocol.commands.call(tokens, context=self.context)
  File "/usr/lib64/python2.7/site-packages/mopidy/mpd/protocol/__init__.py", line 180, in call
    return self.handlers[tokens[0]](context, *tokens[1:])
  File "/usr/lib64/python2.7/site-packages/mopidy/mpd/protocol/__init__.py", line 158, in validate
    return func(**callargs)
  File "/usr/lib64/python2.7/site-packages/mopidy/mpd/protocol/current_playlist.py", line 396, in swap
    song1 = tracks[songpos1]
IndexError: list index out of range

```

**Comment by sticken88** [comment]
I'm not familiar with ncmpcpp. Can you provide info on how to reproduce this?

thanks

**Comment by girst** [comment]
sure! first load a playlist (press `2` to list playlists, then select one, and press space to queue it). then, switch to the queue (`1`) and press CTRL+`R`to reverse it. 

ncmpcpp will after a few secons of silence say "connection refused", because mopidy has crashed. 

I should note, that this crash happens on large playlists like my 1100 songs one, but not on smaller ones.

**Comment by girst** [comment]
i haven't been able to repoduce the crash today. however, i noticed, that when issuing a playlist reversal, a substantial amount of data will be transferred. with tcpflow (https://superuser.com/a/23187) i was able to see that the playlist information was transmitted multiple times (with 11lines per 1100 songs). ncmpcpp by the way uses a lot of `swap id1 id2` statements wrapped in a command-block to reverse a playlist. it takes mpd quite a while to execute these statements, and transmit responses. during that time, 'MPD: no such song' will be shown when I try to start a song. when the transmission has finished, it works again. (this was different a few months ago, when mopidy would crash then.)

I'll close this for now, since I can't reproduce the bug for now. (ncmpcpp was also updated between now and the submission of the bugreport, so maybe they changed something there. I don't have logs for mopidy's updates, since that is not installed with dnf, but pip, which doesn't log by default)

(sorry for the formatting, am in a hurry)

**Comment by girst** [comment]
I think I've managed to narrow down on the bug: it only appears when I've got `py3status` with `mpd_status` running. This addin displays the current title in the status bar, but creates a new connection for every check (~2sec). 

I feel this might be either overwhelming mopidy, or mopidy has some problem with concurrent connections. 

following is the stacktrace from when reversing a >1100 song playlist

```
ERROR    Unhandled exception in MpdFrontend (urn:uuid:369d3808-c656-4e5f-bdb2-ee1df4347795):
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 201, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 295, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/lib64/python2.7/site-packages/mopidy/mpd/actor.py", line 84, in on_event
    self.send_idle(_CORE_EVENTS_TO_IDLE_SUBSYSTEMS[event])
  File "/usr/lib64/python2.7/site-packages/mopidy/mpd/actor.py", line 88, in send_idle
    listener.send(session.MpdSession, subsystem)
  File "/usr/lib64/python2.7/site-packages/mopidy/listener.py", line 27, in send
    'kwargs': kwargs,
  File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 398, in tell
    raise ActorDeadError('%s not found' % self)
ActorDeadError: MpdSession (urn:uuid:7fa93c0b-1ad1-449a-b3ef-e2833d76c609) not found
INFO     New MPD connection from [::1]:58148
INFO     New MPD connection from [::1]:58150
INFO     New MPD connection from [::1]:58152
INFO     New MPD connection from [::1]:58154
INFO     New MPD connection from [::1]:58156
INFO     New MPD connection from [::1]:58158
INFO     New MPD connection from [::1]:58160
INFO     New MPD connection from [::1]:58162
INFO     New MPD connection from [::1]:58164
INFO     New MPD connection from [::1]:58166
INFO     New MPD connection from [::1]:58168
INFO     New MPD connection from [::1]:58170
INFO     New MPD connection from [::1]:58172
INFO     New MPD connection from [::1]:58174
^CINFO     Interrupted. Exiting...
INFO     Stopping Mopidy frontends
INFO     Stopping Mopidy core
INFO     Stopping Mopidy backends
INFO     Stopping Mopidy audio
INFO     Stopping Mopidy mixer
ERROR    There are actor threads still running, this is probably a bug
```
