### ISSUE TITLE
Mopidy Local Scan crash 

### ISSUE THREAD

**Issue by gerroon** [mopidy/mopidy#1656]
Local scan crashes.

https://paste.debian.net/hidden/2a73a099/

I am using Mopidy 2.10 on Debian Testing x64. I running it under my normal user.

**Comment by jodal** [comment]
Copying log output from external pastebin:

```
  Added local:track:XXXXX/declineandfall_bk3_12_gibbon_64kb.mp3                                                                                         
ERROR    2018-01-26 17:49:48,237 [13344:MainThread] mopidy.__main__                                                                                                                                                
  Expected last_modified to be at least 0, not -1354757532000                                                                                                                                                      
Traceback (most recent call last):                                                                                                                                                                                 
  File "/usr/lib/python2.7/dist-packages/mopidy/__main__.py", line 134, in main                                                                                                                                    
    return args.command.run(args, proxied_config)                                                                                                                                                                  
  File "/usr/lib/python2.7/dist-packages/mopidy/local/commands.py", line 151, in run                                                                                                                               
    uri=uri, length=result.duration, last_modified=mtime)                                                                                                                                                          
  File "/usr/lib/python2.7/dist-packages/mopidy/models/immutable.py", line 223, in replace                                                                                                                         
    other = super(ValidatedImmutableObject, self).replace(**kwargs)                                                                                                                                                
  File "/usr/lib/python2.7/dist-packages/mopidy/models/immutable.py", line 120, in replace                                
    other._set_field(key, value)                                                                                       
  File "/usr/lib/python2.7/dist-packages/mopidy/models/immutable.py", line 195, in _set_field                          
    object.__setattr__(self, name, value)                                                                              
  File "/usr/lib/python2.7/dist-packages/mopidy/models/fields.py", line 50, in __set__                                 
    value = self.validate(value)                                                                                          
  File "/usr/lib/python2.7/dist-packages/mopidy/models/fields.py", line 134, in validate                               
    (self._name, self._min, value))                                                                                       
ValueError: Expected last_modified to be at least 0, not -1354757532000                                                
Traceback (most recent call last):                                                                                                                                                                                
  File "/usr/bin/mopidy", line 11, in <module>                                                                         
    load_entry_point('Mopidy==2.1.0', 'console_scripts', 'mopidy')()                                                      
  File "/usr/lib/python2.7/dist-packages/mopidy/__main__.py", line 134, in main                                        
    return args.command.run(args, proxied_config)                                                                         
  File "/usr/lib/python2.7/dist-packages/mopidy/local/commands.py", line 151, in run                                   
    uri=uri, length=result.duration, last_modified=mtime)                                                                 
  File "/usr/lib/python2.7/dist-packages/mopidy/models/immutable.py", line 223, in replace          

   other = super(ValidatedImmutableObject, self).replace(**kwargs)
  File "/usr/lib/python2.7/dist-packages/mopidy/models/immutable.py", line 120, in replace
    other._set_field(key, value)
  File "/usr/lib/python2.7/dist-packages/mopidy/models/immutable.py", line 195, in _set_field
    object.__setattr__(self, name, value)
  File "/usr/lib/python2.7/dist-packages/mopidy/models/fields.py", line 50, in __set__
    value = self.validate(value)
  File "/usr/lib/python2.7/dist-packages/mopidy/models/fields.py", line 134, in validate
    (self._name, self._min, value))
ValueError: Expected last_modified to be at least 0, not -1354757532000
```
