### ISSUE TITLE
Infinite recursion loop in play/next on end of track

### ISSUE THREAD

**Issue by jodal** [mopidy/mopidy#17]
During normal playback both myself and another user has experienced an infinite recursion loop in play/next upon end of track. This probably got to do with the "skip-to-next-track-upon-error" code.

Traceback:

```
... lots of WARNINGs like this ...
WARNING  Play spotify:track:2AVcyZ66hKKKkkFz58Hyhd failed: The track cannot be played
WARNING  Play spotify:track:2AVcyZ66hKKKkkFz58Hyhd failed: The track cannot be played
WARNING  Play spotify:track:2AVcyZ66hKKKkkFz58Hyhd failed: The track cannot be played
WARNING  Play spotify:track:2AVcyZ66hKKKkkFz58Hyhd failed: The track cannot be played
ERROR    maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/jodal/dev/mopidy/mopidy/utils/process.py", line 24, in run
    self.run_inside_try()
  File "/home/jodal/dev/mopidy/mopidy/core.py", line 43, in run_inside_try
    self.process_message(message)
  File "/home/jodal/dev/mopidy/mopidy/core.py", line 88, in process_message
    self.backend.playback.on_end_of_track()
  File "/home/jodal/dev/mopidy/mopidy/backends/base/playback.py", line 317, in on_end_of_track
    self.play(self.cp_track_at_eot)
  File "/home/jodal/dev/mopidy/mopidy/backends/base/playback.py", line 398, in play
    self.next()
  File "/home/jodal/dev/mopidy/mopidy/backends/base/playback.py", line 351, in next
    self.play(self.cp_track_at_next)
  File "/home/jodal/dev/mopidy/mopidy/backends/base/playback.py", line 398, in play
    self.next()
... lots of play() and next() calls ...
```

This is a candidate for a 0.1.1 bugfix release.

**Comment by jcass77** [comment]
As of Mopidy 1.0.5, the skip-to-next-track-upon-error code can also cause an infinite loop if all tracks are unplayable in repeat mode.

Would it not be a good idea to remove unplayable tracks from the tracklist, at least if we are in repeat mode as suggested in PR https://github.com/mopidy/mopidy/pull/1205?
