### ISSUE TITLE
Brew Cleanup now brakes Mopidy.  Gst-Python removed support for Python@2.

### ISSUE THREAD

**Issue by Hamspiced** [mopidy/mopidy#1745]
I just recently upgraded to Mojave.  Pre-Mojave (8 Months ago) i was having issues getting Mopidy to run right fresh.  Figured that out, mostly issues with Python3!=Python2.  So yesteday in doing "Brew Cleanup" i knew something got broke when i saw:
`Removing: /usr/local/Cellar/python@2/2.7.15_2... (4,701 files, 82.7MB)`

Anyways immediately after Mopidy no longer worked.   On run I get:
`RROR: A GObject Python package was not found.

Mopidy requires GStreamer to work. GStreamer is a C library with a
number of dependencies itself, and cannot be installed with the regular
Python tools like pip.

Please see http://docs.mopidy.com/en/latest/installation/ for
instructions on how to install the required dependencies.

Traceback (most recent call last):
  File "/usr/local/bin/mopidy", line 11, in <module>
    load_entry_point('Mopidy==2.2.2', 'console_scripts', 'mopidy')()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/Cellar/mopidy/2.2.2/libexec/lib/python2.7/site-packages/mopidy/__main__.py", line 10, in <module>
    from mopidy import commands, config as config_lib, ext
  File "/usr/local/Cellar/mopidy/2.2.2/libexec/lib/python2.7/site-packages/mopidy/commands.py", line 14, in <module>
    from mopidy.audio import Audio
  File "/usr/local/Cellar/mopidy/2.2.2/libexec/lib/python2.7/site-packages/mopidy/audio/__init__.py", line 4, in <module>
    from .actor import Audio
  File "/usr/local/Cellar/mopidy/2.2.2/libexec/lib/python2.7/site-packages/mopidy/audio/actor.py", line 10, in <module>
    from mopidy.audio import tags as tags_lib, utils
  File "/usr/local/Cellar/mopidy/2.2.2/libexec/lib/python2.7/site-packages/mopidy/audio/tags.py", line 10, in <module>
    from mopidy.internal.gi import GLib, Gst
  File "/usr/local/Cellar/mopidy/2.2.2/libexec/lib/python2.7/site-packages/mopidy/internal/gi.py", line 10, in <module>
    from gi.repository import GLib, GObject, Gst
  File "/usr/local/lib/python2.7/site-packages/gi/importer.py", line 146, in load_module
    dynamic_module = load_overrides(introspection_module)
  File "/usr/local/lib/python2.7/site-packages/gi/overrides/__init__.py", line 125, in load_overrides
    override_mod = importlib.import_module(override_package_name)
  File "/usr/local/Cellar/python@2/2.7.15_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/site-packages/gi/overrides/Gst.py", line 569, in <module>
ImportError: cannot import name _gi_gst`

Same issue i had 8 months ago.  The easy fix was to run: 
`brew reinstall gst-python --without-python --with-python@2`

But now it appears that no longer works because the gst-python homebrew package has now removed support for python@2.

So, is there a way to install the proper gst-python package since the tap has removed support for it.

Since this is part of the Brew script for Mopidy i would assume future installs through brew are broken as well.

I would also recommend no one runs Brew-Cleanup since that is what broke my installation.

**Comment by kingosticks** [comment]
I think this belongs at https://github.com/mopidy/homebrew-mopidy
