### ISSUE TITLE
MPD clients freezing: "ActorDeadError: MpdSession not found"

### ISSUE THREAD

**Issue by harrisonthorne** [mopidy/mopidy#1750]
This issue is with Mopidy 2.2.2.

After a while of playing music (with the spotify and spotify-web extensions), all MPD clients will freeze. Mopidy will play the next song, but the change won't be reflected by the client.

For example, after Song One, Mopidy will audibly play Song Two without a problem, but clients will still read "Song One" until restarted. When restarted, clients will read "Song Two," until Mopidy plays Song Three, when clients will read "Song Two." So, even after clients are restarted, changes to playback won't be registered. Pause/play events don't seem to be recognized either.

I dug into `journalctl` and found this error:

```
Mar 08 15:12:45 hotpocket mopidy[27779]: ERROR    Unhandled exception in MpdFrontend (urn:uuid:c1ea0816-6929-494c-a303-aea5a71a4fca):
Mar 08 15:12:45 hotpocket mopidy[27779]: Traceback (most recent call last):
Mar 08 15:12:45 hotpocket mopidy[27779]:   File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 201, in _actor_loop
Mar 08 15:12:45 hotpocket mopidy[27779]:     response = self._handle_receive(message)
Mar 08 15:12:45 hotpocket mopidy[27779]:   File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 295, in _handle_receive
Mar 08 15:12:45 hotpocket mopidy[27779]:     return callee(*message['args'], **message['kwargs'])
Mar 08 15:12:45 hotpocket mopidy[27779]:   File "/usr/lib/python2.7/site-packages/mopidy/mpd/actor.py", line 90, in on_event
Mar 08 15:12:45 hotpocket mopidy[27779]:     self.send_idle(_CORE_EVENTS_TO_IDLE_SUBSYSTEMS[event])
Mar 08 15:12:45 hotpocket mopidy[27779]:   File "/usr/lib/python2.7/site-packages/mopidy/mpd/actor.py", line 94, in send_idle
Mar 08 15:12:45 hotpocket mopidy[27779]:     listener.send(session.MpdSession, subsystem)
Mar 08 15:12:45 hotpocket mopidy[27779]:   File "/usr/lib/python2.7/site-packages/mopidy/listener.py", line 27, in send
Mar 08 15:12:45 hotpocket mopidy[27779]:     'kwargs': kwargs,
Mar 08 15:12:45 hotpocket mopidy[27779]:   File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 398, in tell
Mar 08 15:12:45 hotpocket mopidy[27779]:     raise ActorDeadError('%s not found' % self)
Mar 08 15:12:45 hotpocket mopidy[27779]: ActorDeadError: MpdSession (urn:uuid:f383a206-85da-422f-81f1-c88ddcbf436f) not found
```

**Comment by jodal** [comment]
The `ActorDeadError` is an effect of an actor having died, and not the root cause. Can you find any other stack traces a bit earlier in the log?

**Comment by harrisonthorne** [comment]
no, that's the only one i've seen.

**Comment by kingosticks** [comment]
> all MPD clients

What exactly do you mean by this? Multiple instances of a particular client - which one? Or every client you have tried - which ones?.

We also probably need a debug log (please use a gist/pastebin) showing the run-up to this occurring.

**Comment by makkanx** [comment]
I think this is same issue as I have and is in #1468

**Comment by harrisonthorne** [comment]
@kingosticks This happens to both `ncmpcpp` and a little [mpd client](https://github.com/harrisonthorne/muse-status/blob/master/mpd/mpd.go) I wrote with [go-mpd](https://github.com/fhs/gompd). I'll get a debug log when I can. :)

**Comment by harrisonthorne** [comment]
[Got this this morning](https://gist.github.com/harrisonthorne/384d27411c6ac65f9d5c95b6cfc9ca00)
