### ISSUE TITLE
Seeking to a non-integer position hangs clients

### ISSUE THREAD

**Issue by roosemberth** [mopidy/mopidy#1756]
Description: as indicated by the title
Expected behaviour: Seeking to a non-integer position should have the same behavior as seeking to integer seconds.

Steps to reproduce: Using [python-mpd2](https://pypi.org/project/python-mpd2/), while playing any song using mopidy:
```
#! /usr/bin/env python3

from mpd import MPDClient

c = MPDClient()
c.connect("localhost", 6600)
c.seekcur('0.1')
```

The above code exits cleanly when using [mpd](https://github.com/MusicPlayerDaemon/MPD) but hangs when using mopidy.

**Comment by jodal** [comment]
From the Mopidy log when reproducing this:

```
ERROR    Unhandled exception in MpdSession (urn:uuid:7f76ab06-22c4-4e35-8230-80bd7e6176cc):
Traceback (most recent call last):
  File "/home/jodal/dev/virtualenvs/mopidy/local/lib/python2.7/site-packages/pykka/_actor.py", line 193, in _actor_loop
    response = self._handle_receive(envelope.message)
  File "/home/jodal/dev/virtualenvs/mopidy/local/lib/python2.7/site-packages/pykka/_actor.py", line 307, in _handle_receive
    return self.on_receive(message)
  File "/home/jodal/mopidy-dev/mopidy/mopidy/internal/network.py", line 423, in on_receive
    self.on_line_received(line)
  File "/home/jodal/mopidy-dev/mopidy/mopidy/mpd/session.py", line 34, in on_line_received
    response = self.dispatcher.handle_request(line)
  File "/home/jodal/mopidy-dev/mopidy/mopidy/mpd/dispatcher.py", line 47, in handle_request
    return self._call_next_filter(request, response, filter_chain)
  File "/home/jodal/mopidy-dev/mopidy/mopidy/mpd/dispatcher.py", line 69, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/home/jodal/mopidy-dev/mopidy/mopidy/mpd/dispatcher.py", line 77, in _catch_mpd_ack_errors_filter
    return self._call_next_filter(request, response, filter_chain)
  File "/home/jodal/mopidy-dev/mopidy/mopidy/mpd/dispatcher.py", line 69, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/home/jodal/mopidy-dev/mopidy/mopidy/mpd/dispatcher.py", line 87, in _authenticate_filter
    return self._call_next_filter(request, response, filter_chain)
  File "/home/jodal/mopidy-dev/mopidy/mopidy/mpd/dispatcher.py", line 69, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/home/jodal/mopidy-dev/mopidy/mopidy/mpd/dispatcher.py", line 106, in _command_list_filter
    response = self._call_next_filter(request, response, filter_chain)
  File "/home/jodal/mopidy-dev/mopidy/mopidy/mpd/dispatcher.py", line 69, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/home/jodal/mopidy-dev/mopidy/mopidy/mpd/dispatcher.py", line 135, in _idle_filter
    response = self._call_next_filter(request, response, filter_chain)
  File "/home/jodal/mopidy-dev/mopidy/mopidy/mpd/dispatcher.py", line 69, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/home/jodal/mopidy-dev/mopidy/mopidy/mpd/dispatcher.py", line 148, in _add_ok_filter
    response = self._call_next_filter(request, response, filter_chain)
  File "/home/jodal/mopidy-dev/mopidy/mopidy/mpd/dispatcher.py", line 69, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/home/jodal/mopidy-dev/mopidy/mopidy/mpd/dispatcher.py", line 160, in _call_handler_filter
    response = self._format_response(self._call_handler(request))
  File "/home/jodal/mopidy-dev/mopidy/mopidy/mpd/dispatcher.py", line 175, in _call_handler
    return protocol.commands.call(tokens, context=self.context)
  File "/home/jodal/mopidy-dev/mopidy/mopidy/mpd/protocol/__init__.py", line 180, in call
    return self.handlers[tokens[0]](context, *tokens[1:])
  File "/home/jodal/mopidy-dev/mopidy/mopidy/mpd/protocol/__init__.py", line 158, in validate
    return func(**callargs)
  File "/home/jodal/mopidy-dev/mopidy/mopidy/mpd/protocol/playback.py", line 381, in seekcur
    position = protocol.UINT(time) * 1000
  File "/home/jodal/mopidy-dev/mopidy/mopidy/mpd/protocol/__init__.py", line 53, in UINT
    raise ValueError('Only positive numbers are allowed')
ValueError: Only positive numbers are allowed
```

Translated to English, Mopidy probably correctly validates that this should be an unsigned int, but isn't. The bug is that it from the client's perspective, Mopidy doesn't handle the problem the same way as the MPD server does.

**Comment by gmkey** [comment]
First finding: I can confirm MPD actually seeks to the position 10.1
