### ISSUE TITLE
UnicodeDecodeError when adding URI containing non-ASCII characters to tracklist MPD

### ISSUE THREAD

**Issue by crocket** [mopidy/mopidy#1759]
mopidy-2.2.2

```
ERROR    Unhandled exception in MpdSession (urn:uuid:76575e20-c10f-46e2-bc60-404ed1cffc27):
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/pykka/actor.py", line 201, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib64/python2.7/site-packages/pykka/actor.py", line 304, in _handle_receive
    return self.on_receive(message)
  File "/usr/lib64/python2.7/site-packages/mopidy/internal/network.py", line 423, in on_receive
    self.on_line_received(line)
  File "/usr/lib64/python2.7/site-packages/mopidy/mpd/session.py", line 34, in on_line_received
    response = self.dispatcher.handle_request(line)
  File "/usr/lib64/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 47, in handle_request
    return self._call_next_filter(request, response, filter_chain)
  File "/usr/lib64/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 69, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/usr/lib64/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 77, in _catch_mpd_ack_errors_filter
    return self._call_next_filter(request, response, filter_chain)
  File "/usr/lib64/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 69, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/usr/lib64/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 87, in _authenticate_filter
    return self._call_next_filter(request, response, filter_chain)
  File "/usr/lib64/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 69, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/usr/lib64/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 106, in _command_list_filter
    response = self._call_next_filter(request, response, filter_chain)
  File "/usr/lib64/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 69, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/usr/lib64/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 135, in _idle_filter
    response = self._call_next_filter(request, response, filter_chain)
  File "/usr/lib64/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 69, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/usr/lib64/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 148, in _add_ok_filter
    response = self._call_next_filter(request, response, filter_chain)
  File "/usr/lib64/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 69, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/usr/lib64/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 160, in _call_handler_filter
    response = self._format_response(self._call_handler(request))
  File "/usr/lib64/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 184, in _format_response
    formatted_response.extend(self._format_lines(element))
  File "/usr/lib64/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 210, in _format_lines
    return ['%s: %s' % (key, value)]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 38: ordinal not in range(128)
```

**Comment by kingosticks** [comment]
Could you give some hints on how someone could reproduce this? We'd want to work out there the bytes came from. Was it from loading an .m3u8 playlist?

**Comment by crocket** [comment]
```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/gi/overrides/GLib.py", line 661, in <lambda>
    func_fdtransform = lambda _, cond, *data: callback(channel, cond, *data)
  File "/usr/lib64/python2.7/site-packages/mopidy/internal/network.py", line 325, in recv_callback
    self.actor_ref.tell({'close': True})
  File "/usr/lib64/python2.7/site-packages/pykka/actor.py", line 398, in tell
    raise ActorDeadError('%s not found' % self)
pykka.exceptions.ActorDeadError: MpdSession (urn:uuid:e1dff601-96bd-488d-ac00-cbb44384db12) not found
```

**Comment by crocket** [comment]
```
WARNING  Could not find a text/uri-list decoder to handle media.
WARNING  GStreamer warning: gst-stream-error-quark: No decoder available for type 'text/uri-list'. (6)
ERROR    GStreamer error: gst-core-error-quark: Your GStreamer installation is missing a plug-in. (12)
```

**Comment by crocket** [comment]
In cantata,
Internet > TuneIn > By Location > Asia > South Korea > All Stations > Any Station in the list.

**Comment by kingosticks** [comment]
So this is a Mopidy-Tunein bug then.

**Comment by crocket** [comment]
> So this is a Mopidy-Tunein bug then.

No. I haven't installed mopidy-tunein. Cantata has its own tunein functionality.

**Comment by crocket** [comment]
I just installed the latest git commit of mopidy-tunein. If I play korean stations from mopidy-tunein, mopidy freezes silently.

**Comment by kingosticks** [comment]
I'm concentrating on the original simpler case of talking MPD to our Stream backend. 

A [full log](https://pastebin.com/udzse1y5) shows this station URI doesn't resolve, which seems to be about right since it doesn't work at https://tunein.com/radio/CBS-Music-FM-939-s14584/ either, at least for me (in the UK). And that's mostly handled OK. Although it seems to be all getting a bit confused in this case because by default Mopidy-Stream has a 5 second timeout, but Cantana gives up much earlier than that and starts a new connection while Mopidy is still working on the original one. Hence the dead actors. I can't see where you configure the timeout in Cantana.

It looks like the exception is because our MPD context doesn't like URIs containing non-ASCII characters. Mopidy's Track URIs are bytes and they get implicitly ASCII decoded when we format the MPD output, and obviously the `뮤직` characters in the fragment part have no ASCII representation. That's a bug there, we should be explicitly handling the `track.uri`. 

Although I don't understand why Cantata even decides to include the fragment. It would be interesting to see if mpd stripped it off or not.
```
Request from [[::ffff:127.0.0.1]:6601]: add "http://opml.radiotime.com/Tune.ashx?id=s14584&locale=en_GB#CBS 뮤직 FM 93.9 (Korean Music)"
```

**Comment by crocket** [comment]
Yo, man. My vivaldi web browser can play https://tunein.com/radio/CBS-Music-FM-939-s14584/
I think CBS Music FM probably blocks connections from outside korea.

**Comment by crocket** [comment]
By the way, the same issue occurs when I open a playlist that contains URLs with unicode URL fragments.

**Comment by kingosticks** [comment]
Yes. I imagine it'll occur when there's any unicode in the uri, even those without fragments. And I'm really surprised why that hasn't come up sooner, or how it escaped our tests. So I need to double check that's actually the case.

**Comment by crocket** [comment]
Preventing MPD clients from causing `pykka.exceptions.ActorDeadError: MpdSession` is important, too.

**Comment by kingosticks** [comment]
I'm not sure of the fix here. Should we be making sure we url-encode all incoming URIs? Or should we be expecting and handling unicode in a `Track.uri`?

**Comment by languitar** [comment]
Will the introduced fix also handle these cases for local media:

```
Oct 13 12:25:35 tank mopidy[589]: UnicodeEncodeError: 'ascii' codec can't encode character u'\xa1' in position 124: ordinal not in range(128)
Oct 13 12:25:35 tank mopidy[589]: Logged from file actor.py, line 312
Oct 13 12:25:35 tank mopidy[589]: WARNING  Setting GStreamer state to GST_STATE_PLAYING failed
Oct 13 12:25:35 tank mopidy[589]: WARNING  Track is not playable: file:///mnt/data/music/Various%20Artists/Putumayo%20Presents_%20%C2%A1Salsa%21/08%20Jos%C3%A9%20Conde%20y%20Ola%20Fresca%20-%20Ay%20Que%2>
Oct 13 12:25:35 tank mopidy[589]: Traceback (most recent call last):
Oct 13 12:25:35 tank mopidy[589]:   File "/usr/lib/python2.7/site-packages/mopidy/internal/log.py", line 176, in emit
Oct 13 12:25:35 tank mopidy[589]:     self.stream.write(message)
Oct 13 12:25:35 tank mopidy[589]: UnicodeEncodeError: 'ascii' codec can't encode character u'\xa1' in position 124: ordinal not in range(128)
Oct 13 12:25:35 tank mopidy[589]: Logged from file actor.py, line 312
Oct 13 12:25:35 tank mopidy[589]: WARNING  Setting GStreamer state to GST_STATE_PLAYING failed
Oct 13 12:25:35 tank mopidy[589]: WARNING  Track is not playable: file:///mnt/data/music/Various%20Artists/Putumayo%20Presents_%20%C2%A1Salsa%21/09%20Ricardo%20Lemvo%20%26%20Makina%20Loca%20-%20Ay%20Vale>
Oct 13 12:25:35 tank mopidy[589]: Traceback (most recent call last):
Oct 13 12:25:35 tank mopidy[589]:   File "/usr/lib/python2.7/site-packages/mopidy/internal/log.py", line 176, in emit
Oct 13 12:25:35 tank mopidy[589]:     self.stream.write(message)
Oct 13 12:25:35 tank mopidy[589]: UnicodeEncodeError: 'ascii' codec can't encode character u'\xa1' in position 124: ordinal not in range(128)
```

**Comment by kingosticks** [comment]
It won't. But  #1817 will.

**Comment by languitar** [comment]
Thanks!
