### ISSUE TITLE
3.0.0: Test suite trips over if mopidy-local extension is not installed

### ISSUE THREAD

**Issue by girst** [mopidy/mopidy#1861]
here's the culprit: https://github.com/mopidy/mopidy/blob/develop/mopidy/local.py

I'm building fedora/rpmfusion packages and stumbled over this (this means, i can't easily install this extension without the main mopidy package available). congrats on finally getting 3.0 out the door :)

```
======================================================================
ERROR: local (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: local
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/builddir/build/BUILD/Mopidy-3.0.0/mopidy/local.py", line 7, in <module>
    from mopidy_local import *  # noqa
ModuleNotFoundError: No module named 'mopidy_local'


----------------------------------------------------------------------
Ran 668 tests in 4.717s

FAILED (errors=1)
Test failed: <unittest.runner.TextTestResult run=668 errors=1 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=668 errors=1 failures=0>
```

**Comment by jodal** [comment]
I'll fix this right away and ship 3.0.1.

Thank you! It feels really great to finally have shipped :-)
