### ISSUE TITLE
installation fails on aarch64 (Armbian) 

### ISSUE THREAD

**Issue by wdehoog** [mopidy/mopidy#1893]
After following the installation instructions at https://mopidy.com/blog/2019/12/27/mopidy-3-faq/#so-how-do-i-install-mopidy-3-on-ubuntu-1804-lts I get:
```
python3.7 -m mopidy

ERROR: A GObject based library was not found.

Mopidy requires GStreamer to work. GStreamer is a C library with a
number of dependencies itself, and cannot be installed with the regular
Python tools like pip.

Please see http://docs.mopidy.com/en/latest/installation/ for
instructions on how to install the required dependencies.

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/mopidy/__main__.py", line 7, in <module>
    from mopidy import commands
  File "/usr/local/lib/python3.7/dist-packages/mopidy/commands.py", line 14, in <module>
    from mopidy.audio import Audio
  File "/usr/local/lib/python3.7/dist-packages/mopidy/audio/__init__.py", line 2, in <module>
    from .actor import Audio
  File "/usr/local/lib/python3.7/dist-packages/mopidy/audio/actor.py", line 8, in <module>
    from mopidy.audio import tags as tags_lib
  File "/usr/local/lib/python3.7/dist-packages/mopidy/audio/tags.py", line 7, in <module>
    from mopidy.internal.gi import GLib, Gst
  File "/usr/local/lib/python3.7/dist-packages/mopidy/internal/gi.py", line 8, in <module>
    from gi.repository import GLib, GObject, Gst
  File "/usr/local/lib/python3.7/dist-packages/gi/importer.py", line 146, in load_module
    dynamic_module = load_overrides(introspection_module)
  File "/usr/local/lib/python3.7/dist-packages/gi/overrides/__init__.py", line 118, in load_overrides
    override_mod = importlib.import_module(override_package_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gst.py", line 569, in <module>
    from . import _gi_gst
ImportError: cannot import name '_gi_gst' from 'gi.overrides' (/usr/local/lib/python3.7/dist-packages/gi/overrides/__init__.py)
```

**Comment by kingosticks** [comment]
Hi, I'm afraid we don't support 18.04, those instructions in the faq are more of a rough suggestion and they are aimed at desktop users (I never specified that, apologies). I would guess the specified GStreamer Python binding overrides you used  are no good for your platform, presumably you didnt use the amd64 ones, you need to find an alternate compatible binary release or build it from source (good luck). If you want to post a new topic at discuss.mopidy.com then perhaps someone will be able to help. But since Mopidy 3 is not supported in 18.04 an issue here isn't appropriate.

**Comment by wdehoog** [comment]
Boehoe... Thanks anyway.

**Comment by wdehoog** [comment]
Correction. Somehow silly me had downloaded the dbg version which failed. When using the deb from http://old-releases.ubuntu.com/ubuntu/pool/universe/g/gst-python1.0/ it starts to work.

**Comment by kingosticks** [comment]
Oh great! Thanks for the update. Glad those 'instructions' are still working.
