### ISSUE TITLE
Mopidy crashes when initializing the keyring

### ISSUE THREAD

**Issue by Gigahawk** [mopidy/mopidy#1894]
Currently using mopidy inside a venv via pipx

If `dbus-python` is installed in the environment, starting mopidy will cause it to crash with 
```
Traceback (most recent call last):
  File "/home/jasper/.local/bin/mopidy", line 8, in <module>
    sys.exit(main())
  File "/home/jasper/.local/pipx/venvs/Mopidy/lib/python3.8/site-packages/mopidy/__main__.py", line 55, in main
    config, config_errors = config_lib.load(
  File "/home/jasper/.local/pipx/venvs/Mopidy/lib/python3.8/site-packages/mopidy/config/__init__.py", line 107, in load
    raw_config = _load(files, defaults, keyring.fetch() + (overrides or []))
  File "/home/jasper/.local/pipx/venvs/Mopidy/lib/python3.8/site-packages/mopidy/config/keyring.py", line 62, in fetch
    attrs = _item_attributes(bus, item_path)
  File "/home/jasper/.local/pipx/venvs/Mopidy/lib/python3.8/site-packages/mopidy/config/keyring.py", line 172, in _item_attributes
    return {bytes(k): bytes(v) for k, v in result.items()}
  File "/home/jasper/.local/pipx/venvs/Mopidy/lib/python3.8/site-packages/mopidy/config/keyring.py", line 172, in <dictcomp>
    return {bytes(k): bytes(v) for k, v in result.items()}
TypeError: string argument without an encoding
```

**Comment by Gigahawk** [comment]
Nevermind, looks like this has already been fixed in develop.
