### ISSUE TITLE
Browsing a File track raises a NotADirectoryError exception

### ISSUE THREAD

**Issue by kingosticks** [mopidy/mopidy#1906]
The `uri` argument for `LibraryController.browse` should be a directory rather than a file but the File backend raises an unhandled exception when we pass one to it. We should handle this more gracefully.
```
FileBackend-2 DEBUG    2020-05-07 14:06:45,889 Browsing files at: file:///home/nick/Music/Tall%20Ships%20-%20Chemistry.mp3
Core-7 ERROR    2020-05-07 14:06:45,889 FileBackend backend caused an exception.
Traceback (most recent call last):
  File "/home/nick/Dev/mopidy-dev/mopidy/mopidy/core/library.py", line 17, in _backend_error_handling
    yield
  File "/home/nick/Dev/mopidy-dev/mopidy/mopidy/core/library.py", line 114, in _browse
    result = backend.library.browse(uri).get()
  File "/usr/lib/python3/dist-packages/pykka/_threading.py", line 45, in get
    _compat.reraise(*self._data['exc_info'])
  File "/usr/lib/python3/dist-packages/pykka/_compat/__init__.py", line 29, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 193, in _actor_loop
    response = self._handle_receive(envelope.message)
  File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 299, in _handle_receive
    return callee(*message.args, **message.kwargs)
  File "/home/nick/Dev/mopidy-dev/mopidy/mopidy/file/library.py", line 55, in browse
    for dir_entry in local_path.iterdir():
  File "/usr/lib/python3.8/pathlib.py", line 1113, in iterdir
    for name in self._accessor.listdir(self):
NotADirectoryError: [Errno 20] Not a directory: '/home/nick/Music/Tall Ships - Chemistry.mp3'
```

**Comment by parth-verma** [comment]
Hey, I want to take this up. What is the behaviour expected here?

**Comment by kingosticks** [comment]
Catch the exception and just the log the error. If we need to return something (I've not looked again to remind myself), return None.
