### ISSUE TITLE
Unhandled exception in Audio: 'TypeError: cannot convert 'Error' object to bytes'

### ISSUE THREAD

**Issue by kingosticks** [mopidy/mopidy#1924]
```
Jul 09 13:46:56 raspberrypi mopidy[510]: ERROR    [Audio-2] mopidy.audio.actor Failed to create audio output "Headphone": gst_parse_error: no element "Headph
Jul 09 13:46:56 raspberrypi mopidy[510]: ERROR    [Audio-2] pykka Unhandled exception in Audio (urn:uuid:40bdf253-6264-45b3-bfb1-41f03423c3c1):
Jul 09 13:46:56 raspberrypi mopidy[510]: Traceback (most recent call last):
Jul 09 13:46:56 raspberrypi mopidy[510]:   File "/usr/lib/python3/dist-packages/mopidy/audio/actor.py", line 125, in add_output
Jul 09 13:46:56 raspberrypi mopidy[510]:     description, ghost_unlinked_pads=True
Jul 09 13:46:56 raspberrypi mopidy[510]: gi.repository.GLib.GError: gst_parse_error: no element "Headphone" (1)
Jul 09 13:46:56 raspberrypi mopidy[510]: During handling of the above exception, another exception occurred:
Jul 09 13:46:56 raspberrypi mopidy[510]: Traceback (most recent call last):
Jul 09 13:46:56 raspberrypi mopidy[510]:   File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 186, in _actor_loop
Jul 09 13:46:56 raspberrypi mopidy[510]:     self.on_start()
Jul 09 13:46:56 raspberrypi mopidy[510]:   File "/usr/lib/python3/dist-packages/mopidy/audio/actor.py", line 458, in on_start
Jul 09 13:46:56 raspberrypi mopidy[510]:     self._setup_outputs()
Jul 09 13:46:56 raspberrypi mopidy[510]:   File "/usr/lib/python3/dist-packages/mopidy/audio/actor.py", line 507, in _setup_outputs
Jul 09 13:46:56 raspberrypi mopidy[510]:     self._outputs.add_output(self._config["audio"]["output"])
Jul 09 13:46:56 raspberrypi mopidy[510]:   File "/usr/lib/python3/dist-packages/mopidy/audio/actor.py", line 131, in add_output
Jul 09 13:46:56 raspberrypi mopidy[510]:     raise exceptions.AudioException(bytes(ex))
Jul 09 13:46:56 raspberrypi mopidy[510]: TypeError: cannot convert 'Error' object to bytes
```

**Comment by rohitgeddam** [comment]
I want to work on this!!

**Comment by kingosticks** [comment]
Please feel free to do so.

**Comment by abid1998** [comment]
@kingosticks I can start working on this if you can point me to a direction. I am a new contributor.
