### ISSUE TITLE
Invalid logging verbosity config values raise exception

### ISSUE THREAD

**Issue by kingosticks** [mopidy/mopidy#1947]
**Describe the bug**
Invalid logging verbosity configurations are not handled gracefully. i.e. verbosity levels outside the valid range of 0 to 4

**To reproduce**
```
(mopidy3) nick@xps:~/Dev/mopidy-dev$ mopidy -o logging/verbosity=5
Traceback (most recent call last):
  File "/home/nick/.virtualenvs/mopidy3/bin/mopidy", line 11, in <module>
    load_entry_point('Mopidy', 'console_scripts', 'mopidy')()
  File "/home/nick/Dev/mopidy-dev/mopidy/mopidy/__main__.py", line 65, in main
    log.setup_logging(
  File "/home/nick/Dev/mopidy-dev/mopidy/mopidy/internal/log.py", line 63, in setup_logging
    verbosity_level = get_verbosity_level(
  File "/home/nick/Dev/mopidy-dev/mopidy/mopidy/internal/log.py", line 86, in get_verbosity_level
    result = base_verbosity_level + config["logging"]["verbosity"]
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
```

**Expected behaviour**
Should print an error message and use the default config value instead. 

**Environment (please complete the following information):**
Latest development branch of Mopidy.

**Comment by kingosticks** [comment]
`logging/verbosity` is an integer in the inclusive range 0 to 4 as per https://github.com/mopidy/mopidy/blob/a0fa850ccce5a1f61a58599354341a4275f9090a/mopidy/config/__init__.py#L45 

Which means our value of 5 is invalid and gets converted to `None` by our config validation. And then we try and do addition with that later, which Python doesnt like. We could just fix the config's max value and/or the use of None bugs but... there is a perfectly good looking `LogLevel` type that would be nicer to use than an integer and already supports trace level 5. That would be a breaking change unless we upgraded LogLevel to also handle integers. @jodal you touched near this recently, any thoughts?

**Comment by jodal** [comment]
The verbosity doesn't map directly to log levels. It turns on a more verbose log level for Mopidy than for dependencies. Because of that, I think we should keep it as an integer and just fix the crash when the value is outside the accepted range.
