### ISSUE TITLE
Mopidy doesn't run on OpenBSD

### ISSUE THREAD

**Issue by bigodel** [mopidy/mopidy#1973]
I remeber that some time ago I managed to make Mopidy work on OpenBSD without much issues, but today when I finally installed OpenBSD back on my machine, I managed to install Mopidy and GStreamer plugins succesfully, but when trying to run Mopidy I get the following excpetion:
```
Traceback (most recent call last):
  File "/home/bigodel/.local/bin/mopidy", line 8, in <module>
    sys.exit(main())
  File "/home/bigodel/.local/lib/python3.8/site-packages/mopidy/__main__.py", line 62, in main
    create_core_dirs(config)
  File "/home/bigodel/.local/lib/python3.8/site-packages/mopidy/__main__.py", line 158, in crea
    path.get_or_create_dir(config["core"]["data_dir"])
  File "/home/bigodel/.local/lib/python3.8/site-packages/mopidy/internal/path.py", line 15, in
    dir_path = expand_path(dir_path)
  File "/home/bigodel/.local/lib/python3.8/site-packages/mopidy/internal/path.py", line 73, in
    path = str(pathlib.Path(path))
  File "/usr/local/lib/python3.8/pathlib.py", line 1041, in __new__
    self = cls._from_parts(args, init=False)
  File "/usr/local/lib/python3.8/pathlib.py", line 682, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/local/lib/python3.8/pathlib.py", line 666, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
It appears to me that some internal function from Mopidy is trying to access the value of `XDG_DATA_DIR` (shouldn't it be `XDG_DATA_HOME` as per [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)?) but for some reason it is returning None. I'm not very well versed on Python, but I could try and take a look into it to give more meaningful feedback.

**Comment by bigodel** [comment]
I also noticed that Mopidy doesn't seem to accept comments in the same line as configuration options in the configuration file. So something like

```
[audio]

**Comment by kingosticks** [comment]
> I also noticed that Mopidy doesn't seem to accept comments in the same line as configuration options in the configuration file.

Yes, that is https://github.com/mopidy/mopidy/issues/1868

**Comment by bigodel** [comment]
> > I also noticed that Mopidy doesn't seem to accept comments in the same line as configuration options in the configuration file.
> 
> Yes, that is #1868

Ah, ok, hadn't looked for this particular issue as it is just a minor inconvenience.
