### ISSUE TITLE
Mopidy not starting 

### ISSUE THREAD

**Issue by nerdlikeme** [mopidy/mopidy#2070]
If you are not sure about anything below then please post on our [forum](https://discourse.mopidy.com/) first.

**Describe the bug**
A clear and concise description of what the bug is. Is this specific to a particular Backend (e.g. Mopidy-Spotify), Frontend (e.g. Mopidy-MPD) or client?

**How to reproduce**
Steps to reproduce the behaviour including any error messages that occur.

**Expected behaviour**

**Environment**
Please complete the following information:
- Operating system (e.g. Debian Buster, Ubuntu 20.04)
- [Running Mopidy](https://docs.mopidy.com/en/latest/running/) as a service or in the terminal?
- Your config (output of `sudo mopidyctl config`)
- Software versions (output of `sudo mopidyctl deps`)
- Any specific hardware (e.g. an exotic USB soundcard)

**Additional context**
Add any other context about the problem here. If appropriate, upload an [appropriately verbose](https://docs.mopidy.com/en/latest/troubleshooting/#debug-logging) log file showing the bug.

cat /etc/os-release >>>>>>>>>>>>>>>>>>

PRETTY_NAME="Debian GNU/Linux bookworm/sid"
NAME="Debian GNU/Linux"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

sudo mopidyctl config >>>>>>>>>>>>>>>>>>>>

pi@raspberrypi:~ $ sudo mopidyctl config
Running "/usr/bin/mopidy --config /usr/share/mopidy/conf.d:/etc/mopidy/mopidy.conf config" as user mopidy
Traceback (most recent call last):
  File "/usr/bin/mopidy", line 33, in <module>
    sys.exit(load_entry_point('Mopidy==3.1.1', 'console_scripts', 'mopidy')())
  File "/usr/bin/mopidy", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/dist-packages/mopidy/__init__.py", line 5, in <module>
    import pkg_resources
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 3249, in <module>
    def _initialize_master_working_set():
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 3223, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 3261, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 619, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 632, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 1044, in __init__
    self.scan(search_path)
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 1077, in scan
    self.add(dist)
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 1096, in add
    dists.sort(key=operator.attrgetter('hashcmp'), reverse=True)
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 2631, in hashcmp
    self.parsed_version,
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 2685, in parsed_version
    raise packaging.version.InvalidVersion(f"{str(ex)} {info}") from None
pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: '1.14.0-unknown' (package: gpg)

sudo systemctl status mopidy >>>>>>>>>>>>>>>>>>>>>>>>>>

pi@raspberrypi:~ $ sudo systemctl status mopidy
● mopidy.service - Mopidy music server
     Loaded: loaded (/lib/systemd/system/mopidy.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sun 2023-01-29 21:32:21 IST; 16min ago
    Process: 15656 ExecStartPre=/bin/mkdir -p /var/cache/mopidy (code=exited, status=0/SUCCESS)
    Process: 15657 ExecStartPre=/bin/chown mopidy:audio /var/cache/mopidy (code=exited, status=0/SUCCESS)
    Process: 15658 ExecStart=/usr/bin/mopidy --config /usr/share/mopidy/conf.d:/etc/mopidy/mopidy.conf (code=exited, status=1/FAILURE)
   Main PID: 15658 (code=exited, status=1/FAILURE)
        CPU: 622ms

Jan 29 21:32:21 raspberrypi mopidy[15658]:     self.add(dist)
Jan 29 21:32:21 raspberrypi mopidy[15658]:   File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 1096, in add
Jan 29 21:32:21 raspberrypi mopidy[15658]:     dists.sort(key=operator.attrgetter('hashcmp'), reverse=True)
Jan 29 21:32:21 raspberrypi mopidy[15658]:   File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 2631, in hashcmp
Jan 29 21:32:21 raspberrypi mopidy[15658]:     self.parsed_version,
Jan 29 21:32:21 raspberrypi mopidy[15658]:   File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 2685, in parsed_version
Jan 29 21:32:21 raspberrypi mopidy[15658]:     raise packaging.version.InvalidVersion(f"{str(ex)} {info}") from None
Jan 29 21:32:21 raspberrypi mopidy[15658]: pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: '1.14.0-unknown' (package: gpg)
Jan 29 21:32:21 raspberrypi systemd[1]: mopidy.service: Main process exited, code=exited, status=1/FAILURE
Jan 29 21:32:21 raspberrypi systemd[1]: mopidy.service: Failed with result 'exit-code'.

journalctl -u mopidy -r >>>>>>>>>>>>>>>>>>>>

-- Journal begins at Sun 2023-01-01 07:05:01 IST, ends at Sun 2023-01-29 21:48:36 IST. --
Jan 29 21:32:21 raspberrypi systemd[1]: mopidy.service: Failed with result 'exit-code'.
Jan 29 21:32:21 raspberrypi systemd[1]: mopidy.service: Main process exited, code=exited, status=1/FAILURE
Jan 29 21:32:21 raspberrypi mopidy[15658]: pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: '1.14.0-unknown' (package: gpg)
Jan 29 21:32:21 raspberrypi mopidy[15658]:     raise packaging.version.InvalidVersion(f"{str(ex)} {info}") from None
Jan 29 21:32:21 raspberrypi mopidy[15658]:   File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 2685, in parsed_version
Jan 29 21:32:21 raspberrypi mopidy[15658]:     self.parsed_version,
Jan 29 21:32:21 raspberrypi mopidy[15658]:   File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 2631, in hashcmp
Jan 29 21:32:21 raspberrypi mopidy[15658]:     dists.sort(key=operator.attrgetter('hashcmp'), reverse=True)
Jan 29 21:32:21 raspberrypi mopidy[15658]:   File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 1096, in add
Jan 29 21:32:21 raspberrypi mopidy[15658]:     self.add(dist)
Jan 29 21:32:21 raspberrypi mopidy[15658]:   File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 1077, in scan
Jan 29 21:32:21 raspberrypi mopidy[15658]:     self.scan(search_path)
Jan 29 21:32:21 raspberrypi mopidy[15658]:   File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 1044, in __init__
Jan 29 21:32:21 raspberrypi mopidy[15658]:     dists = ws.resolve(reqs, Environment())
Jan 29 21:32:21 raspberrypi mopidy[15658]:   File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 632, in _build_from_requirements
Jan 29 21:32:21 raspberrypi mopidy[15658]:     return cls._build_from_requirements(__requires__)
Jan 29 21:32:21 raspberrypi mopidy[15658]:   File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 619, in _build_master
Jan 29 21:32:21 raspberrypi mopidy[15658]:     working_set = WorkingSet._build_master()
Jan 29 21:32:21 raspberrypi mopidy[15658]:   File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 3261, in _initialize_master_working_set
Jan 29 21:32:21 raspberrypi mopidy[15658]:     f(*args, **kwargs)
Jan 29 21:32:21 raspberrypi mopidy[15658]:   File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 3223, in _call_aside
Jan 29 21:32:21 raspberrypi mopidy[15658]:     def _initialize_master_working_set():
Jan 29 21:32:21 raspberrypi mopidy[15658]:   File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 3249, in <module>
Jan 29 21:32:21 raspberrypi mopidy[15658]:     import pkg_resources
Jan 29 21:32:21 raspberrypi mopidy[15658]:   File "/usr/local/lib/python3.9/dist-packages/mopidy/__init__.py", line 5, in <module>
Jan 29 21:32:21 raspberrypi mopidy[15658]:   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
Jan 29 21:32:21 raspberrypi mopidy[15658]:   File "<frozen importlib._bootstrap_external>", line 790, in exec_module
Jan 29 21:32:21 raspberrypi mopidy[15658]:   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
Jan 29 21:32:21 raspberrypi mopidy[15658]:   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
Jan 29 21:32:21 raspberrypi mopidy[15658]:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
Jan 29 21:32:21 raspberrypi mopidy[15658]:   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
Jan 29 21:32:21 raspberrypi mopidy[15658]:   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
Jan 29 21:32:21 raspberrypi mopidy[15658]:   File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
Jan 29 21:32:21 raspberrypi mopidy[15658]:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
Jan 29 21:32:21 raspberrypi mopidy[15658]:   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
Jan 29 21:32:21 raspberrypi mopidy[15658]:     return _bootstrap._gcd_import(name[level:], package, level)
Jan 29 21:32:21 raspberrypi mopidy[15658]:   File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
Jan 29 21:32:21 raspberrypi mopidy[15658]:     module = import_module(match.group('module'))
Jan 29 21:32:21 raspberrypi mopidy[15658]:   File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
Jan 29 21:32:21 raspberrypi mopidy[15658]:     return next(matches).load()
Jan 29 21:32:21 raspberrypi mopidy[15658]:   File "/usr/bin/mopidy", line 25, in importlib_load_entry_point
Jan 29 21:32:21 raspberrypi mopidy[15658]:     sys.exit(load_entry_point('Mopidy==3.1.1', 'console_scripts', 'mopidy')())
Jan 29 21:32:21 raspberrypi mopidy[15658]:   File "/usr/bin/mopidy", line 33, in <module>
Jan 29 21:32:21 raspberrypi mopidy[15658]: Traceback (most recent call last):
Jan 29 21:32:20 raspberrypi systemd[1]: Started Mopidy music server.
Jan 29 21:32:20 raspberrypi systemd[1]: Starting Mopidy music server...
Jan 29 20:47:00 raspberrypi systemd[1]: mopidy.service: Failed with result 'exit-code'.
Jan 29 20:47:00 raspberrypi systemd[1]: mopidy.service: Main process exited, code=exited, status=1/FAILURE
Jan 29 20:47:00 raspberrypi mopidy[994]: pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: '1.14.0-unknown' (package: gpg)
Jan 29 20:47:00 raspberrypi mopidy[994]:     raise packaging.version.InvalidVersion(f"{str(ex)} {info}") from None

sudo mopidyctl deps >>>>>>>>>>>>>>>>>>>

pi@raspberrypi:~ $ sudo mopidyctl deps
Running "/usr/bin/mopidy --config /usr/share/mopidy/conf.d:/etc/mopidy/mopidy.conf deps" as user mopidy
Traceback (most recent call last):
  File "/usr/bin/mopidy", line 33, in <module>
    sys.exit(load_entry_point('Mopidy==3.1.1', 'console_scripts', 'mopidy')())
  File "/usr/bin/mopidy", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/dist-packages/mopidy/__init__.py", line 5, in <module>
    import pkg_resources
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 3249, in <module>
    def _initialize_master_working_set():
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 3223, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 3261, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 619, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 632, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 1044, in __init__
    self.scan(search_path)
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 1077, in scan
    self.add(dist)
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 1096, in add
    dists.sort(key=operator.attrgetter('hashcmp'), reverse=True)
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 2631, in hashcmp
    self.parsed_version,
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 2685, in parsed_version
    raise packaging.version.InvalidVersion(f"{str(ex)} {info}") from None
pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: '1.14.0-unknown' (package: gpg)

**Comment by kingosticks** [comment]
You've not stated the version of Mopidy you are trying to install and I can't work it out from the traceback (which may be a hint). Is it latest from source, latest from apt.mopidy.com or whatever old thing is in Debian testing?

**Comment by nerdlikeme** [comment]
Sir, I am using Mopidy Version No 3.4.1 installed from apt.mopidy.com. Thanks for the help.

**Comment by nerdlikeme** [comment]
pi@raspberrypi:~ $ cat /usr/bin/mopidy
#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'Mopidy==3.1.1','console_scripts','mopidy'
import re
import sys

# for compatibility with easy_install; see #2198
__requires__ = 'Mopidy==3.1.1'

try:
    from importlib.metadata import distribution
except ImportError:
    try:
        from importlib_metadata import distribution
    except ImportError:
        from pkg_resources import load_entry_point


def importlib_load_entry_point(spec, group, name):
    dist_name, _, _ = spec.partition('==')
    matches = (
        entry_point
        for entry_point in distribution(dist_name).entry_points
        if entry_point.group == group and entry_point.name == name
    )
    return next(matches).load()


globals().setdefault('load_entry_point', importlib_load_entry_point)


if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(load_entry_point('Mopidy==3.1.1', 'console_scripts', 'mopidy')())

**Comment by kingosticks** [comment]
The output there would suggest you have Mopidy 3.1 installed. Maybe check it's looking at apt.mopidy.com. Although, either way, I'm not sure why we are getting this error.

**Comment by nerdlikeme** [comment]
Resolved

pi@raspberrypi:~ $ mopidy -v

**DEBUG    2023-01-31 13:25:09,798 [10869:MainThread] mopidy.ext
  Validating extension: spotify_tunigo
WARNING  2023-01-31 13:25:09,943 [10869:MainThread] py.warnings
  /home/pi/.local/lib/python3.9/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 1.14.0-unknown is an invalid version and will not be supported in a future release**

pi@raspberrypi:~ $ sudo pip uninstall Mopidy-Spotify-Tunigo



pi@raspberrypi:~ $ sudo systemctl status mopidy
● mopidy.service - Mopidy music server
     Loaded: loaded (/lib/systemd/system/mopidy.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2023-01-31 13:40:13 IST; 15min ago
    Process: 12471 ExecStartPre=/bin/mkdir -p /var/cache/mopidy (code=exited, status=0/SUCCESS)
    Process: 12472 ExecStartPre=/bin/chown mopidy:audio /var/cache/mopidy (code=exited, status=0/SUCCESS)
   Main PID: 12474 (mopidy)
      Tasks: 34 (limit: 4915)
        CPU: 11.944s
     CGroup: /system.slice/mopidy.service
             └─12474 /usr/bin/python3 /usr/bin/mopidy --config /usr/share/mopidy/conf.d:/etc/mopidy/mopidy.conf

Jan 31 13:45:18 raspberrypi mopidy[12474]: ERROR    [MainThread] mopidy.audio.gst GStreamer error: Could not open file "/tmp/snapfifo" for writing.
Jan 31 13:45:18 raspberrypi mopidy[12474]: WARNING  [Audio-2] mopidy.audio.actor Setting GStreamer state to GST_STATE_PLAYING failed
Jan 31 13:45:18 raspberrypi mopidy[12474]: WARNING  [Core-9] mopidy.core.tracklist Track is not playable: local:track:_Somewhere%20In%20Time_%20-%20Complete%20Soundtrack.mp3
Jan 31 13:52:11 raspberrypi mopidy[12474]: INFO     [Thread-1452] mopidy_iris.system Running system action 'local_scan'
Jan 31 13:52:11 raspberrypi mopidy[12474]: ERROR    [Thread-1452] mopidy_iris.system Password-less access to file:///usr/local/lib/python3.9/dist-packages/mopidy_iris/system.sh was refused. Check your /etc/su>
Jan 31 13:52:11 raspberrypi mopidy[12474]: ERROR    [Thread-1452] mopidy_iris.system Password-less access to file:///usr/local/lib/python3.9/dist-packages/mopidy_iris/system.sh was refused. Check your /etc/su>
Jan 31 13:54:12 raspberrypi mopidy[12474]: WARNING  [MainThread] mopidy.audio.gst GStreamer warning: Wav stream not finished properly
Jan 31 13:54:19 raspberrypi mopidy[12474]: WARNING  [MainThread] mopidy.audio.gst GStreamer warning: Wav stream not finished properly
Jan 31 13:54:36 raspberrypi mopidy[12474]: WARNING  [MainThread] mopidy.audio.gst GStreamer warning: Wav stream not finished properly
Jan 31 13:54:38 raspberrypi mopidy[12474]: WARNING  [MainThread] mopidy.audio.gst GStreamer warning: Wav stream not finished properly
