### ISSUE TITLE
Mopidy doesn't install on OS X

### ISSUE THREAD

**Issue by paulsturgess** [mopidy/mopidy#673]
I'm trying to install Mopidy 0.18.1 on OS X Mavericks.

I've followed [the OS X installation instructions](http://docs.mopidy.com/en/latest/installation/#os-x-install-from-homebrew-and-pip) and everything appeared to install correctly.

However, Mopdiy will not start...

```
$ mopidy
```

```
Traceback (most recent call last):
  File "/usr/local/bin/mopidy", line 9, in <module>
    load_entry_point('Mopidy==0.18.1', 'console_scripts', 'mopidy')()
  File "build/bdist.macosx-10.9-intel/egg/pkg_resources.py", line 353, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "build/bdist.macosx-10.9-intel/egg/pkg_resources.py", line 2302, in load_entry_point
    return ep.load()
  File "build/bdist.macosx-10.9-intel/egg/pkg_resources.py", line 2029, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.7/site-packages/mopidy/__main__.py", line 28, in <module>
    from mopidy import commands, ext
  File "/usr/local/lib/python2.7/site-packages/mopidy/commands.py", line 13, in <module>
    from mopidy.audio import Audio
  File "/usr/local/lib/python2.7/site-packages/mopidy/audio/__init__.py", line 4, in <module>
    from .actor import Audio
  File "/usr/local/lib/python2.7/site-packages/mopidy/audio/actor.py", line 3, in <module>
    import pygst
ImportError: No module named pygst
```

**Comment by vespakoen** [comment]
Same here, on Xubuntu 14.04

**Comment by jodal** [comment]
This issue was about OS X and was closed half a year ago.

Please ask for help on https://discuss.mopidy.com/, and provide more details of how you installed Mopidy and the exact commands you run and their output.
