### ISSUE TITLE
ImportError: No module named gobject

### ISSUE THREAD

**Issue by zopyx** [mopidy/mopidy#836]
I have no idea why Mopidy can't install dependencies itself. It is truly annoying and unprofessional if you can not such a featured module out-of-the-box without further hassles. The error happens on Mac and Linux.

``` python
suxmac:mopidy ajung$ bin/mopidy 
Traceback (most recent call last):
  File "bin/mopidy", line 9, in <module>
    load_entry_point('Mopidy==0.19.3', 'console_scripts', 'mopidy')()
  File "/private/tmp/mopidy/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/private/tmp/mopidy/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/private/tmp/mopidy/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/private/tmp/mopidy/lib/python2.7/site-packages/mopidy/__main__.py", line 8, in <module>
    import gobject
ImportError: No module named gobject
```

**Comment by bobf** [comment]
"completely unprofessional" = insulting open source software developers you've never met. :(
