### ISSUE TITLE
subsonic with tls/ssl does not work

### ISSUE THREAD

**Issue by d4b3n** [mopidy/mopidy#946]
2015-01-21 23:28:16,651 - INFO     Connecting to Subsonic library https://penny.hiddenhostname.net:8443 as user BBen
2015-01-21 23:28:20,857 - ERROR    Uncaught exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mopidy/commands.py", line 272, in run
    backends = self.start_backends(config, backend_classes, audio)
  File "/usr/local/lib/python2.7/dist-packages/mopidy/commands.py", line 343, in start_backends
    config=config, audio=audio).proxy()
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 93, in start
    obj = cls(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mopidy_subsonic/actor.py", line 32, in __init__
    self.playlists = SubsonicPlaylistsProvider(backend=self)
  File "/usr/local/lib/python2.7/dist-packages/mopidy_subsonic/playlist.py", line 15, in __init__
    self.playlists = self._get_playlists()
  File "/usr/local/lib/python2.7/dist-packages/mopidy_subsonic/playlist.py", line 36, in _get_playlists
    playlists = self.remote.get_user_playlists()
  File "/usr/local/lib/python2.7/dist-packages/mopidy_subsonic/client.py", line 353, in get_user_playlists
    results = self.api.getPlaylists().get('playlists')
  File "/usr/local/lib/python2.7/dist-packages/libsonic/connection.py", line 573, in getPlaylists
    res = self._doInfoReq(req)
  File "/usr/local/lib/python2.7/dist-packages/libsonic/connection.py", line 2257, in _doInfoReq
    res = self._opener.open(req)
  File "/usr/lib/python2.7/urllib2.py", line 401, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 419, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 379, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/libsonic/connection.py", line 61, in https_open
    return self.do_open(HTTPSConnectionChain, req)
  File "/usr/lib/python2.7/urllib2.py", line 1178, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 962, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 996, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 958, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 818, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 794, in send
    self.sock.sendall(data)
AttributeError: 'NoneType' object has no attribute 'sendall'
2015-01-21 23:28:20,888 - INFO     Stopping Mopidy frontends
2015-01-21 23:28:20,892 - INFO     Stopping Mopidy core
2015-01-21 23:28:20,895 - INFO     Stopping Mopidy backends
2015-01-21 23:28:20,905 - INFO     Stopping Mopidy-Podcast directories
2015-01-21 23:28:20,930 - INFO     Stopping Mopidy audio
2015-01-21 23:28:20,944 - INFO     Stopping Mopidy mixer
2015-01-21 23:28:32,070 - INFO     Starting Mopidy 0.19.5

**Comment by adamcik** [comment]
You probably want to create a bug against the mopidy-subsonic repo and not mopidy itself for the https part. If this exception leaves mopidy in an unusable state we should probably be catching actor startup errors (which I think we might already have a bug for). As we should be more resilient against extension bugs where we can.

**Comment by adamcik** [comment]
Closing this bug as we should follow this up in #667
