### ISSUE TITLE
MPD UnicodeDecodeError

### ISSUE THREAD

**Issue by ropert** [mopidy/mopidy#971]
Normal Loglevel shows this:

``` python
2015-02-04 06:30:11,901 ERROR [3714:MpdSession-27] pykka: Unhandled exception in MpdSession (urn:uuid:9595028c-486c-4c89-813a-785c3cafc057):
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 200, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 303, in _handle_receive
    return self.on_receive(message)
  File "/usr/lib/python2.7/dist-packages/mopidy/utils/network.py", line 366, in on_receive
    self.on_line_received(line)
  File "/usr/lib/python2.7/dist-packages/mopidy/mpd/session.py", line 41, in on_line_received
    self.send_lines(response)
  File "/usr/lib/python2.7/dist-packages/mopidy/utils/network.py", line 428, in send_lines
    self.connection.queue_send(self.encode(data))
  File "/usr/lib/python2.7/dist-packages/mopidy/utils/network.py", line 189, in queue_send
    self.send_buffer = self.send(self.send_buffer + data)
  File "/usr/lib/python2.7/dist-packages/mopidy/utils/network.py", line 202, in send
    self.stop('Unexpected client error: %s' % e)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 16: ordinal not in range(128)
```

With Debbuging:

``` python
file: local:track:Datarock/Kein%20Titel/11%20AudioTrack%2011.mp3
    Time: 236
    Artist: Datarock
    Title: AudioTrack 11
    Album: Kein Titel
    Track: 11
    Genre: Unbekannt
    OK
ERROR    2015-02-04 06:30:11,901 [3714:MpdSession-27] pykka
  Unhandled exception in MpdSession (urn:uuid:9595028c-486c-4c89-813a-785c3cafc057):
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 200, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 303, in _handle_receive
    return self.on_receive(message)
  File "/usr/lib/python2.7/dist-packages/mopidy/utils/network.py", line 366, in on_receive
    self.on_line_received(line)
  File "/usr/lib/python2.7/dist-packages/mopidy/mpd/session.py", line 41, in on_line_received
    self.send_lines(response)
  File "/usr/lib/python2.7/dist-packages/mopidy/utils/network.py", line 428, in send_lines
    self.connection.queue_send(self.encode(data))
  File "/usr/lib/python2.7/dist-packages/mopidy/utils/network.py", line 189, in queue_send
    self.send_buffer = self.send(self.send_buffer + data)
  File "/usr/lib/python2.7/dist-packages/mopidy/utils/network.py", line 202, in send
    self.stop('Unexpected client error: %s' % e)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 16: ordinal not in range(128)
DEBUG    2015-02-04 06:30:12,098 [3714:MpdSession-27] pykka
  Unregistered MpdSession (urn:uuid:9595028c-486c-4c89-813a-785c3cafc057)
```

Then I change followd the advice from Mopidy Discuss (https://discuss.mopidy.com/t/mpd-error-after-successful-connect/566):

```
    file: local:track:Datarock/Kein%20Titel/11%20AudioTrack%2011.mp3
    Time: 236
    Artist: Datarock
    Title: AudioTrack 11
    Album: Kein Titel
    Track: 11
    Genre: Unbekannt
    OK
DEBUG    2015-02-10 16:49:56,626 [4213:MpdSession-11] mopidy.utils.network
  Unexpected client error: error(32, 'Daten\xc3\xbcbergabe unterbrochen (broken pipe)')
DEBUG    2015-02-10 16:49:57,131 [4213:MainThread] pykka
  Registered MpdSession (urn:uuid:18e5db5c-fda7-4ee7-a183-7d84fdcff1ac)
DEBUG    2015-02-10 16:49:57,074 [4213:MpdSession-11] mopidy.mpd.session
  Request from [192.168.1.8]:56642: close
DEBUG    2015-02-10 16:49:57,177 [4213:MainThread] pykka
  Starting MpdSession (urn:uuid:18e5db5c-fda7-4ee7-a183-7d84fdcff1ac)
DEBUG    2015-02-10 16:49:57,296 [4213:MpdSession-11] mopidy.mpd.session
  Response to [192.168.1.8]:56642: OK
DEBUG    2015-02-10 16:49:57,408 [4213:MpdSession-11] mopidy.utils.network
  Already stopping: Unexpected client error: error(9, 'Bad file descriptor')
INFO     2015-02-10 16:49:57,312 [4213:MpdSession-28] mopidy.mpd.session
  New MPD connection from [192.168.1.8]:56663
DEBUG    2015-02-10 16:49:57,499 [4213:MpdSession-11] mopidy.utils.network
  Already stopping: Client most likely disconnected.
```

Sometimes later I got this erors and mopidy shutsdown after that:

``` python
ERROR    2015-02-10 16:57:56,253 [4213:MpdSession-20] pykka
  Unhandled exception in MpdSession (urn:uuid:68c56fc8-6342-41e4-b36d-ddc812875bc7):
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 200, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 303, in _handle_receive
    return self.on_receive(message)
  File "/usr/lib/python2.7/dist-packages/mopidy/utils/network.py", line 366, in on_receive
    self.on_line_received(line)
  File "/usr/lib/python2.7/dist-packages/mopidy/mpd/session.py", line 39, in on_line_received
    formatting.indent(self.terminator.join(response)))
  File "/usr/lib/python2.7/dist-packages/mopidy/utils/formatting.py", line 13, in indent
    result = linebreak.join(lines)
MemoryError
DEBUG    2015-02-10 16:57:58,386 [4213:MpdSession-21] mopidy.utils.network
  Already stopping: Client most likely disconnected.
DEBUG    2015-02-10 16:57:58,434 [4213:MpdSession-20] pykka
  Unregistered MpdSession (urn:uuid:68c56fc8-6342-41e4-b36d-ddc812875bc7)
DEBUG    2015-02-10 16:57:58,507 [4213:MpdSession-21] pykka
  Unregistered MpdSession (urn:uuid:7af306aa-f2fe-4219-983f-dea5006c99b3)
DEBUG    2015-02-10 16:57:58,572 [4213:MpdSession-21] pykka
  Stopped MpdSession (urn:uuid:7af306aa-f2fe-4219-983f-dea5006c99b3)
DEBUG    2015-02-10 16:58:00,096 [4213:MpdSession-21] mopidy.utils.network
  Already stopping: Actor is shutting down.
DEBUG    2015-02-10 16:58:12,092 [4213:MainThread] mopidy.utils.network
  Already stopping: Client inactive for 60s; closing connection
DEBUG    2015-02-10 16:58:58,021 [4213:MpdSession-22] mopidy.utils.network
  Unexpected client error: error(32, 'Daten\xc3\xbcbergabe unterbrochen (broken pipe)')
DEBUG    2015-02-10 16:58:59,892 [4213:MpdSession-22] mopidy.mpd.session
  Request from [192.168.1.8]:56654: close
DEBUG    2015-02-10 16:58:59,938 [4213:MainThread] mopidy.utils.network
  Already stopping: Client inactive for 60s; closing connection
DEBUG    2015-02-10 16:59:00,001 [4213:MpdSession-22] mopidy.mpd.session
  Response to [192.168.1.8]:56654: OK
DEBUG    2015-02-10 16:59:00,004 [4213:MpdSession-22] mopidy.utils.network
  Already stopping: Unexpected client error: error(9, 'Bad file descriptor')
DEBUG    2015-02-10 16:59:00,093 [4213:MpdSession-22] mopidy.utils.network
  Already stopping: Client most likely disconnected.
DEBUG    2015-02-10 16:59:00,193 [4213:MpdSession-22] pykka
  Unregistered MpdSession (urn:uuid:710e58dd-1bf7-44d4-aaee-67cadedd419e)
DEBUG    2015-02-10 16:59:00,254 [4213:MpdSession-22] pykka
  Stopped MpdSession (urn:uuid:710e58dd-1bf7-44d4-aaee-67cadedd419e)
DEBUG    2015-02-10 16:59:00,291 [4213:MpdSession-22] mopidy.utils.network
  Already stopping: Actor is shutting down.
DEBUG    2015-02-10 17:00:04,191 [4213:MainThread] mopidy.utils.network
  Already stopping: Client inactive for 60s; closing connection
ERROR    2015-02-10 17:00:44,073 [4213:MpdSession-24] pykka
  Unhandled exception in MpdSession (urn:uuid:64d515a1-f2f1-454d-bc9e-c4eebb06c4ed):
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 200, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 303, in _handle_receive
    return self.on_receive(message)
  File "/usr/lib/python2.7/dist-packages/mopidy/utils/network.py", line 366, in on_receive
    self.on_line_received(line)
  File "/usr/lib/python2.7/dist-packages/mopidy/mpd/session.py", line 39, in on_line_received
    formatting.indent(self.terminator.join(response)))
  File "/usr/lib/python2.7/dist-packages/mopidy/utils/formatting.py", line 13, in indent
    result = linebreak.join(lines)
MemoryError
```

*Edit:* Formatted Mopidy output. -@jodal

**Comment by jodal** [comment]
The problem here is naive logging of error messages originating from libc's `strerror()`, which is localized depending on the system's locale, and thus may contain non-ASCII chars.

The `MemoryError` you have is probably due to the system being out of memory. Can you confirm that? If so, it's not much we can do with that.

**Comment by ropert** [comment]
I run mopidy on a RasberryPi B+. With Raspbian, fresh installed and uptodate.

**Comment by kingosticks** [comment]
In regards to being out of memory, have you tried altering the amount of ram allocated to the GPU? If you don't use a display then you can set it to the minimum split (I think it's 8MB). Might be enough if you're lucky.

**Comment by adamcik** [comment]
Don't think this is anything we can reasonably fix specifically in mopidy other than trying to reduce the memory usage. Closing as I don't think there is anything directly actionable in this bug.

**Comment by jodal** [comment]
I agree there's not much to do with the MemoryError, but we should review all logging of `strerror()` based exception messages and make sure they are decoded using the the system's locale/filesystem encoding.
