### ISSUE TITLE
Create a merge function on models?

### ISSUE THREAD

**Issue by adamcik** [mopidy/mopidy#972]
To replace code like https://github.com/mopidy/mopidy/commit/b7ed2b8681dd9e9c7b5a49a16226a6b37b7e09d5#diff-4fefa5e8daee129b7d1a76b0bcd7fc65R124 or at least internalize it to models.

**Comment by adamcik** [comment]
Following crash highlights the need for solving this in models and not add hock all over the place:

```
2015-03-01 22:39:28,088 ERROR    [Core-7] build/bdist.linux-x86_64/egg/pykka/actor.py:268
  pykka Unhandled exception in Core (urn:uuid:10cdae76-e7bf-4409-a482-732b475104d0):
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/pykka/actor.py", line 200, in _actor_loop
    response = self._handle_receive(message)
  File "build/bdist.linux-x86_64/egg/pykka/actor.py", line 294, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/home/adamcik/dev/mopidy/mopidy/listener.py", line 49, in on_event
    getattr(self, event)(**kwargs)
  File "/home/adamcik/dev/mopidy/mopidy/core/actor.py", line 139, in tags_changed
    'track': Track(**track_kwargs)})
  File "/home/adamcik/dev/mopidy/mopidy/models.py", line 393, in __init__
    super(Track, self).__init__(*args, **kwargs)
  File "/home/adamcik/dev/mopidy/mopidy/models.py", line 20, in __init__
    key)
TypeError: __init__() got an unexpected keyword argument "_spotify_track"
```

**Comment by adamcik** [comment]
I think we are going to avoid having a need for this as I'm planing on changing the code in question. Closing.

**Comment by jodal** [comment]
Also, the specific problem here was `SpotifyTrack` which goes away with Mopidy-Spotify 1.
